Carrying - Add system
Savage-Game-Design/Across-the-Fence pull request #101
Opened 2023-12-01 18:42 UTC by veteran29

- title

2023-12-01 20:51 UTC, Spoffy requested changes

2023-12-01 20:51 UTC, Spoffy commented on game/functions/systems/carry/client/fn_carry_doCarry.sqf
> +[_target, "AinjPfalMstpSnonWrflDnon_carried_Up"] remoteExec ["switchMove", 0];
It feels weird to me that we trigger this clientside, before confirming with the server that we're able to do the attach. 

Would it reduce the risk of weird situations cropping up, if we triggered all this on the server, only after the server's confirmed we can attach?

2023-12-01 20:51 UTC, Spoffy commented on game/functions/systems/carry/server/remoteExec/fn_carry_attachRequest.sqf
> +    };
If we abort here, we're already attached because of doCarry, and have variables set. I think we need to roll a bunch of things back?

2023-12-01 20:51 UTC, Spoffy commented on game/functions/systems/carry/client/fn_carry_doCarry.sqf
> +[_target, "AinjPfalMstpSnonWrflDnon_carried_Up"] remoteExec ["switchMove", 0];
(Same for line 30 - where we set the variable)

2023-12-01 20:51 UTC, Spoffy commented on game/functions/systems/carry/server/remoteExec/fn_carry_attachRequest.sqf
> +    _target switchMove "vn_carried_still";
Does switchMove need remoteExec'ing here?

2023-12-01 20:51 UTC, Spoffy commented on game/functions/systems/carry/server/remoteExec/fn_carry_detachRequest.sqf
> +    ] select (lifeState _target == "INCAPACITATED"))] remoteExec ["switchMove"];
Do need an `alive` check here too, in case the player being dropped is dead?

2023-12-06 22:09 UTC, veteran29 commented on game/functions/systems/carry/client/fn_carry_doCarry.sqf
> +[_target, "AinjPfalMstpSnonWrflDnon_carried_Up"] remoteExec ["switchMove", 0];
According to Robs feedback I've removed the animations and will use short hold actions instead. Everything animation related is now done on the server.

2023-12-06 22:09 UTC, veteran29 commented on game/functions/systems/carry/server/remoteExec/fn_carry_attachRequest.sqf
> +    };
Dismissing as it's not relevant after removal of animations.

2023-12-06 22:10 UTC, veteran29 commented on game/functions/systems/carry/server/remoteExec/fn_carry_attachRequest.sqf
> +    _target switchMove "vn_carried_still";
It did, switchMove needs local target

2023-12-06 22:11 UTC, veteran29 commented on game/functions/systems/carry/server/remoteExec/fn_carry_detachRequest.sqf
> +    ] select (lifeState _target == "INCAPACITATED"))] remoteExec ["switchMove"];
It shouldn't be needed, dying unit will use "face down" anim and then ragdoll.

2023-12-11 21:08 UTC, Spoffy requested changes

2023-12-11 21:08 UTC, Spoffy commented on game/functions/systems/carry/client/remoteExec/fn_carry_attachResponse.sqf
> +_unit setVariable ["vgm_carry_carriedObject", _target];
Feels like the server should control this, or this should be broadcast over the network. 

Setting it globally on the server in some situations, and locally on just the carrying client in others, feels like it could lead to edge cases where there's a mismatch between clients.

2023-12-11 21:10 UTC, veteran29 commented on game/functions/systems/carry/client/remoteExec/fn_carry_attachResponse.sqf
> +_unit setVariable ["vgm_carry_carriedObject", _target];
I agree, this is leftover of the old implementation with animations and is already broadcasted from server so doing it again here is redundant.

2023-12-11 22:30 UTC, Spoffy approved these changes

2023-12-12 01:17 UTC, merged