Mission Objects - Add system #VGM-223
Savage-Game-Design/Across-the-Fence pull request #111
Opened 2023-12-20 20:57 UTC by veteran29

Adds basic framework that allows creation of "virtual" items which are spawned as local objects on the clients participating in the mission. Objects do not exist on the server or clients not in the mission which improves performance.

Provides:
- create function which "registers" the object in the mission
- delete function which removes the virtual item on the server and object instance on the clients
- virtual objects created before mission start will be automatically instanced by the clients
- virtual objects created during the mission need to be sent to the clients, easy API function provided

2023-12-23 23:02 UTC, Spoffy requested changes
Looks great! Couple of comments, but this looks perfect for both the scouting/hint objects and oddities! 

For the latter, I wonder if it's worth spawning a copy on the server to make sure AI pathfinding doesn't get messed with?

2023-12-23 23:02 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_startMission.sqf
> +// TODO what should setup objects in the mission?
Probably the director, but not 100% sure right now. No change needed here, just commenting :)

2023-12-23 23:02 UTC, Spoffy commented on game/functions/systems/mission_objects/server/fn_mission_objects_spawnObjects.sqf
> +};
This looks to generate a hashmap, but clientside spawnObjects looks to expect an array. Do we need `_allMissionsObjects get _x`? Or will an array of IDs suffice?

2023-12-23 23:02 UTC, Spoffy commented on game/functions/systems/mission_objects/client/fn_mission_objects_spawnObjects.sqf
> +    _object setDir _dir;
Should we disable simulation or maybe use a simple object? Wondering for desync reasons due to gravity, being knocked, etc

2024-01-04 02:42 UTC, veteran29 commented on game/functions/systems/mission_objects/server/fn_mission_objects_spawnObjects.sqf
> +};
Client side expects hashmap in the format this `if` generates. This converts array of IDs into a "chunk" which allows us to send only the objects we want to less network load.

2024-01-04 02:43 UTC, veteran29 commented on game/functions/systems/mission_objects/client/fn_mission_objects_spawnObjects.sqf
> +    _object setDir _dir;
Made it so it uses simple objects by default, and if there's an init code it will use object with simulation disabled (simple objects do not support actions)

2024-01-05 17:42 UTC, veteran29 commented
Objects are spawned also on the server now.

2024-01-08 17:20 UTC, Spoffy commented on game/functions/systems/mission_objects/server/fn_mission_objects_spawnObjects.sqf
> +};
Ah, got it. And yup, I see the line I didm't see before in the clientside script now :D

2024-01-08 17:23 UTC, Spoffy approved these changes

2024-01-08 17:37 UTC, merged