Skill Investigate - Add component
Savage-Game-Design/Across-the-Fence pull request #112
Opened 2024-01-22 01:53 UTC by veteran29

- title

Thanks to HorribleGoat for noise texture.

2024-01-25 16:57 UTC, Spoffy requested changes

2024-01-25 16:57 UTC, Spoffy commented on game/functions/systems/skill_investigate/client/script_component.inc
> +#define WAVE3_TIME 1.6
Are these are the time thresholds, in seconds, when that wave starts showing?

If so, maybe we could use `WAVE1_START_TIME`, as it would make the logic a little easier to understand :)

2024-01-25 16:57 UTC, Spoffy commented on game/functions/systems/skill_investigate/client/fn_skill_investigate_setListenMode.sqf
> +    } forEachReversed vgm_c_skill_investigate_noises;
Would this simplify to:
```suggestion
    vgm_c_skill_investigate_noises select { !( _x call vgm_c_fnc_skill_investigate_drawSoundWaves) }
```
?

2024-01-27 03:32 UTC, veteran29 commented on game/functions/systems/skill_investigate/client/fn_skill_investigate_setListenMode.sqf
> +    } forEachReversed vgm_c_skill_investigate_noises;
Good catch, it will be a lot faster too. Just needs an assignment as `select` does not modify input array.
```sqf
// Execution Time: 0.0050 ms  |  Cycles: 10000/10000  |  Total Time: 50 ms
test_array = [false, true, true, false, false, true];
{
	private _completed = _x;
	if (_completed) then {test_array deleteAt _forEachIndex};
} forEachReversed test_array;
```
```sqf
// Execution Time: 0.0017 ms  |  Cycles: 10000/10000  |  Total Time: 17 ms
test_array = [false, true, true, false, false, true];

test_array = test_array select {!_x};
```

2024-01-27 14:47 UTC, Spoffy approved these changes

2024-01-27 14:52 UTC, merged