AI - Add basic tree for enemy AI
Savage-Game-Design/Across-the-Fence pull request #118
Opened 2024-02-16 00:01 UTC by Spoffy

Requires compiler branch to be merged first.

2024-03-23 16:19 UTC, veteran29 requested changes

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/ai/global/fn_ai_tickAllBehaviourTrees.sqf
> +        [parameter] call vn_fnc_myFunction
Example

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +		_units - Array of unit classes [Array, defaults to [] (empty array)]
I would rename this to `_unitClasses` as `_units` suggests it's an array of objects.

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +_group setVariable ["vgm_g_missionId", _missionId, true];
Reliable messages arrive in the order they're sent, I would move `setGroupOwner` to the bottom so it arrives on the client after all public variables are set.
```suggestion
private _selectedClient = call para_s_fnc_loadbal_suggest_host;
_group setVariable ["behaviourEnabled", false, true];
_group setVariable ["vgm_g_missionId", _missionId, true];
[_group, ["enemyAI"] call vgm_g_fnc_btree_getCompiledTree] call vgm_g_fnc_btree_setTree;

_group setVariable ["groupClientOwner", _selectedClient];
_group setGroupOwner _selectedClient;
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +    if (local _group) then {
```suggestion
    params ["_group", "_local"];
    if (_local) then {
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +    if (local _group) then {
This will only happen for group that transfer from client back to server, intentional?

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +        _group setVariable ["groupClientOwner", clientOwner, true];
`clientOwner` gives me the vibe you wanted this to work for every client, "Local" EH works only where it is transferring FROM and TO

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_setWaypoint.sqf
> +	_group setCurrentWaypoint _waypoint;
```suggestion
    _group setCurrentWaypoint _waypoint;
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_setWaypoint.sqf
> +	_waypoint setWaypointType _type;
```suggestion
    _waypoint setWaypointType _type;
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_moveTo_execute.sqf
> +private _destPos = _group getVariable ["vgm_l_btree_moveTo_destination", getPos _groupLeader];
`getPos <object>` is a bad command and should be avoided most of the time. It can get really slow due to surface checks.
```suggestion
private _destPos = _group getVariable ["vgm_l_btree_moveTo_destination", getPosATL _groupLeader];
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_moveTo_start.sqf
> +        [createHashMap, []] call vgm_g_fnc_btree_action_moveTo;
Invalid example.

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_moveTo_start.sqf
> +    [_group, "AUTO"] call vgm_g_fnc_btree_setGroupStance;
Shouldn't that use UP to prevent them from going prone on contact? Not sure what's the intention here, reset the stance for force it.

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_action_patrolArea.sqf
> +		Makes the group patrol around a point.
No tabs!
```suggestion
        Makes the group patrol around a point.
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_action_patrolArea.sqf
> +    private _patrolCenter = _extern_blackboard getOrDefaultCall ["patrolAreaCenter", { getPos leader _group }, true];
It looks like the leader could be used directly without a need to get his position here.
```suggestion
    private _patrolCenter = _extern_blackboard getOrDefaultCall ["patrolAreaCenter", {leader _group}, true];
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_action_patrolArea.sqf
> +    private _nextAngle = (_patrolCenter getDir getPos leader _group) + _patrolAngleChange;
```suggestion
    private _nextAngle = (_patrolCenter getDir getPosATL leader _group) + _patrolAngleChange;
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_action_patrolArea.sqf
> +	_extern_group setFormation "COLUMN";
```suggestion
    _extern_group setCombatMode "RED";
    _extern_group setBehaviour "SAFE";
    _extern_group setFormation "COLUMN";
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_action_moveToInvestigationPoint.sqf
> +	_extern_group setFormation "COLUMN";
```suggestion
    _extern_group setCombatMode "RED";
    _extern_group setBehaviour "AWARE";
    _extern_group setFormation "COLUMN";
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_setGroupStance.sqf
> +	false
```suggestion
    {
        _x setUnitPos _pos;
    } forEach units _group;
    _group setVariable ["vgm_l_btree_unitPos", _pos];
    false
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_decorator_updateKnowledgeService.sqf
> +        _blackboard set ["lastDangerEvent", serverTime];
I would advise to use `time`, `serverTime` is seconds since the server process start so it does not change when missions are restarted.

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/runner/global/fn_btree_setTree.sqf
> +        if (!local _group) then {
I'm not even sure how `local <object>` behaves inside that EH, `_local` param should be used.
```suggestion
        params ["_group", "_local"];

        // Cleanup the behaviour tree on the old host.
        // Makes sure the nodes are correctly aborted, and unassigned callbacks fire.
        // TODO - Might need to consider race conditions here, if this gets done *after* the assignment on other host,
        // and anything behaves globally.
        if (!_local) then {
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/runner/global/fn_btree_setTree.sqf
> +            [_group] call vgm_g_fnc_btree_setTree;
Not a fan of reusing the `setTree` for aborting the bTree.

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/trees/global/fn_btree_tree_enemyAI.sqf
> +        [parameter] call vgm_X_fnc_component_myFunction
Rest of the header above needs filling.
```suggestion
        [] call vgm_g_fnc_btree_tree_enemyAI
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/behaviour_trees/trees/global/fn_btree_preInit_compiledTrees.sqf
> +    File: fn_btree_tree_preInit.sqf
File name does not match header file name. I would shorten the file name to `_preInit`

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/danger_reporting/client/fn_dangerReport_playerFiredManHandler.sqf
> +    private _config = (configFile >> "CfgAmmo" >> (typeOf _projectile));
```suggestion
    private _config = configOf _projectile;
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/danger_reporting/client/fn_dangerReport_playerFiredManHandler.sqf
> +_projectile addEventHandler ["Explode", {
We could calculate handler type and parameters per ammo class and cache it.

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/danger_reporting/client/fn_dangerReport_preInit.sqf
> +    ["playerId", getPlayerID player],
`player` should not be used in preInit as it can be null in here. You can move this to `postInit`

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/danger_reporting/client/fn_dangerReport_preInit.sqf
> +            [format ["Attempting to disabled danger reporting, but it's already disabled", player]] call vgm_g_fnc_logWarning;
```suggestion
            [format ["Attempting to disable danger reporting, but it's already disabled", player]] call vgm_g_fnc_logWarning;
```

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/suppression/global/fn_suppression_add.sqf
> +    _unit setVariable ["vgm_l_suppression_decayWindowStart", serverTime];
As earlier I would advise to use `time`.

2024-03-23 16:19 UTC, veteran29 commented on game/functions/systems/suppression/global/fn_suppression_setShooterMultiplier.sqf
> +_shooter setVariable ["vgm_g_suppression_multiplier", _multiplier, true];
We should plug this into the coefficients so skills affect this.

2024-04-02 15:12 UTC, Spoffy commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +    if (local _group) then {
Nice catch, thanks :D

2024-04-02 15:13 UTC, Spoffy commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +        _group setVariable ["groupClientOwner", clientOwner, true];
Yeah, I think you're right, this needs work.

2024-04-02 16:01 UTC, Spoffy commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_moveTo_execute.sqf
> +private _destPos = _group getVariable ["vgm_l_btree_moveTo_destination", getPos _groupLeader];
Didn't know it had slowdown edge cases! Thanks for the heads up. I'll fix this here, and fix any other instances as I come across them later.

2024-04-02 16:05 UTC, Spoffy commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_moveTo_start.sqf
> +    [_group, "AUTO"] call vgm_g_fnc_btree_setGroupStance;
This is quite old code, I believe the original intention was to undo any setUnitPos to "DOWN" the rest of the code might have made.
I'm inclined to leave this for now and monitor, as I think "UP" is more likely to mess with other areas of the behaviour tree right now.

2024-04-02 16:12 UTC, Spoffy commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_action_patrolArea.sqf
> +    private _patrolCenter = _extern_blackboard getOrDefaultCall ["patrolAreaCenter", { getPos leader _group }, true];
I think that would be different. The location they're patrolling around would change with the leader's position then, rather than being statically set at their current location.

2024-04-02 16:13 UTC, Spoffy commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_decorator_updateKnowledgeService.sqf
> +        _blackboard set ["lastDangerEvent", serverTime];
Shouuuld be fine, trees should be all local so shouldn't be an issue.

2024-04-02 16:43 UTC, Spoffy commented on game/functions/systems/behaviour_trees/runner/global/fn_btree_setTree.sqf
> +            [_group] call vgm_g_fnc_btree_setTree;
I'm thinking of it as "Setting the currently running btree to nil". 
I can pull it out into a separate func if you think it's worthwhile.

2024-04-02 16:44 UTC, Spoffy commented on game/functions/systems/behaviour_trees/trees/global/fn_btree_preInit_compiledTrees.sqf
> +    File: fn_btree_tree_preInit.sqf
There's already a "btree_preInit" for the runner. Could do a `btree_trees` prefix on the func, similar to the one the code has here?

2024-04-02 16:46 UTC, Spoffy commented on game/functions/systems/danger_reporting/client/fn_dangerReport_playerFiredManHandler.sqf
> +    private _config = (configFile >> "CfgAmmo" >> (typeOf _projectile));
Nice, didn't know about this! Huge timesaver.

2024-04-02 16:48 UTC, Spoffy commented on game/functions/systems/danger_reporting/client/fn_dangerReport_preInit.sqf
> +    ["playerId", getPlayerID player],
This reminds me of why I made the custom init process in paradigm, it had guarantees like that xD

2024-04-03 00:52 UTC, Spoffy commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +    if (local _group) then {
Should be fixed, redid this so it should activate the behaviour tree again whenever the group is moved.

2024-04-03 00:54 UTC, Spoffy commented on game/functions/systems/danger_reporting/client/fn_dangerReport_preInit.sqf
> +    ["playerId", getPlayerID player],
Moved this whole file to postInit.

2024-04-19 15:27 UTC, veteran29 requested changes

2024-04-19 15:27 UTC, veteran29 commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +}]] remoteExec ["addEventHandler", 0];
this won't handle JIP. Move adding that EH to global function and something like this on clients in postInit to support it:
```
{
    _x call vgm_g_fnc_btree_handleLocalityChange;
} forEach (allGroups select {!isNil {_x getVariable "groupClientOwner"}});

2024-04-19 15:27 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_setGroupStance.sqf
> +        _force - Runs the set position command, even if they're already set in that pos. [BOOLEAN]
This param is unused

2024-04-19 15:27 UTC, veteran29 commented on game/functions/systems/behaviour_trees/ai_utilities/global/fn_btree_tracking_findNearbyTracks.sqf
> +    getPos leader _group,
```suggestion
    getPosATL leader _group,
```

2024-04-19 15:27 UTC, veteran29 commented on game/functions/systems/behaviour_trees/runner/global/fn_btree_setTree.sqf
> +    _group addEventHandler ["Local", {
Can groups change locality multiple times, if so this should remove the EH when it sets the tree to `nil` or have a guard to prevent adding the EH multiple times.

2024-04-19 15:27 UTC, veteran29 commented on game/functions/systems/tracking/global/fn_tracking_preInit.sqf
> +
```suggestion

```

2024-04-21 16:33 UTC, veteran29 commented on game/functions/systems/danger_reporting/client/fn_dangerReport_preInit.sqf
> +    ["playerId", getPlayerID player],
> This reminds me of why I made the custom init process in paradigm, it had guarantees like that xD

Post init also has such guarantees. Pre init is just before everything is initialized as the name suggests :P

2024-04-21 16:34 UTC, veteran29 commented on game/functions/systems/behaviour_trees/trees/global/fn_btree_preInit_compiledTrees.sqf
> +    File: fn_btree_tree_preInit.sqf
Yes please, rename with a prefix to keep the naming convention or rename to `_init` and call in `btree_preInit`

2024-04-21 16:49 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_action_patrolArea.sqf
> +    private _patrolCenter = _extern_blackboard getOrDefaultCall ["patrolAreaCenter", { getPos leader _group }, true];
```suggestion
    private _patrolCenter = _extern_blackboard getOrDefaultCall ["patrolAreaCenter", { getPosATL leader _group }, true];
```

2024-04-21 16:57 UTC, veteran29 commented on game/functions/systems/tracking/global/fn_tracking_recordTracks.sqf
> +params ["_trackingGroup"];
Is this tracking group or track**ed** group, seeing that we record the positions of these groups I think the latter is better name.

2024-04-21 17:00 UTC, veteran29 commented on game/functions/systems/tracking/global/fn_tracking_recordTracks.sqf
> +        private _pos = getPos _x;
```suggestion
        private _pos = getPosATL _x;
```

2024-05-03 15:39 UTC, Spoffy commented on game/functions/systems/ai/server/fn_ai_createEnemySquad.sqf
> +}]] remoteExec ["addEventHandler", 0];
Nice catch, will fix :)

2024-05-03 15:39 UTC, Spoffy commented on game/functions/systems/behaviour_trees/runner/global/fn_btree_setTree.sqf
> +    _group addEventHandler ["Local", {
They shouldn't, but I can't rule it out happening in the future. Put a fix in for this :)

2024-05-03 22:31 UTC, Spoffy commented on game/functions/systems/tracking/global/fn_tracking_recordTracks.sqf
> +params ["_trackingGroup"];
Both? It's a way of aggregating tracking info, so each mission is isolated from the others.

trackingNamespace might be an idea for this? or trackedNamespace?

2024-07-05 19:35 UTC, veteran29 commented on game/functions/systems/behaviour_trees/trees/global/fn_btree_preInit_compiledTrees.sqf
> +    File: fn_btree_tree_preInit.sqf
FIle in comment still does not match the file name.

2024-07-05 19:39 UTC, veteran29 approved these changes

2024-07-17 15:36 UTC, merged