Locational Events - Add system
Savage-Game-Design/Across-the-Fence pull request #119
Opened 2024-02-23 02:15 UTC by Spoffy

Adds a system for listening to events in specific locations, broadcast over the network (or local).

Intention is for this to be used for the AI perception system.

2024-03-01 01:12 UTC, veteran29 requested changes
Some minor nitpicks ;)

2024-03-01 01:12 UTC, veteran29 commented on game/functions/systems/locational_events/global/fn_locEvents_preInit.sqf
> +        The initialised events data [HashMap]
With the convention we're using this function should run "by itself" via `preInit = 1` config. If it's supposed to be executed by other function it should be named just `_init`.

2024-03-01 01:12 UTC, veteran29 commented on game/functions/systems/locational_events/global/fn_locEvents_preInit.sqf
> +localNamespace getVariable "vgm_l_locEvents_data";
Faster on average and easier to follow the flow IMO:
```suggestion
private _locEventsData = localNamespace getVariable "vgm_l_locEvents_data";

if (isNil "_locEventsData") then {
    _locEventsData = createHashMapFromArray [
        ["listenerEventTypes", createHashMap],
        ["perceptionGroups", createHashMap]
    ];

    localNamespace setVariable ["vgm_l_locEvents_data", _locEventsData];
};

_locEventsData // return
```

2024-03-01 01:12 UTC, veteran29 commented on game/functions/systems/locational_events/global/fn_locEvents_removeHandlers.sqf
> +    };
```suggestion
    if (isNil "_listenerDetails") then {continue};
```

2024-03-01 01:12 UTC, veteran29 commented on game/functions/systems/locational_events/global/fn_locEvents_triggerEvent.sqf
> +};
```suggestion
if (_isLocal) exitWith {
    _arguments call vgm_g_fnc_locEvents_callHandlers;
};

_arguments remoteExecCall ["vgm_g_fnc_locEvents_callHandlers", 0];
```

2024-03-01 01:12 UTC, veteran29 commented on game/functions/systems/locational_events/global/fn_locEvents_callHandlers.sqf
> +        _perceptionGroup - The perception group ID to send the event to [STRING]
As mentioned in chat I think we should rename it to something like `_eventNamespace` or `_eventGroup`. In all of the functions

2024-03-01 13:52 UTC, Spoffy commented on game/functions/systems/locational_events/global/fn_locEvents_preInit.sqf
> +        The initialised events data [HashMap]
Honestly not sure what the right approach here is - I do both with this 😆 

It's preInit'd, but also called from `onNearbyEvents` just in case we end up trying to register handlers in the preInit code anywhere else.

Happy to follow whatever you reccommend here 🙂

2024-03-01 13:54 UTC, Spoffy commented on game/functions/systems/locational_events/global/fn_locEvents_preInit.sqf
> +localNamespace getVariable "vgm_l_locEvents_data";
Wise move, I like it.

2024-03-01 14:03 UTC, Spoffy commented on game/functions/systems/locational_events/global/fn_locEvents_callHandlers.sqf
> +        _perceptionGroup - The perception group ID to send the event to [STRING]
Done!

2024-03-01 19:12 UTC, veteran29 commented on game/functions/systems/locational_events/global/fn_locEvents_preInit.sqf
> +        The initialised events data [HashMap]
It's not preInited, the function does not have the tag in the config. I would just rename it to init and call it only from `onNearbyEvents`, it's behind `isNil` check that's fired every time anyway now.

2024-03-02 18:16 UTC, Spoffy commented on game/functions/systems/locational_events/global/fn_locEvents_preInit.sqf
> +        The initialised events data [HashMap]
I'll add it to preInit, as the other functions will break unless I add the init code to all of them, which isn't something I'd like to do.

There's because there's no guarantee when `onNearbyEvents` will be called for the first time, and the rest of the functions assume the events data already exists.

2024-03-04 18:33 UTC, veteran29 approved these changes
LGTM

2024-03-04 19:04 UTC, merged