Add Arma server launch command to run.py #388ef13
Savage-Game-Design/Across-the-Fence pull request #12
Opened 2022-12-14 16:31 UTC by veteran29

- title

2022-12-14 16:31 UTC, SavageGameDesign commented
Task linked: [CU-388ef13 Add Server launch command to run.py](https://app.clickup.com/t/388ef13)

2023-01-03 23:44 UTC, Spoffy requested changes

2023-01-03 23:44 UTC, Spoffy commented on build/config.example.py
> +paradigm_path = config_dir.parent /  "paradigm"
Is this a bug? - we're now doing `Path(__file__).parent.parent`

2023-01-03 23:44 UTC, Spoffy commented on build/config.example.py
> +arma_server_config_path = Path(__file__).parent /  "arma_server.hpp"
Do we want to reuse `config_dir` here since it's now defined on line 5?

2023-01-03 23:44 UTC, Spoffy commented on build/run.py
> +    try_create_arma_server_mission_dir(mpmissions_dir, mission_output_dir)
Maybe `try_symlink` would be clearer here. instead of `try_create`?

2023-01-03 23:44 UTC, Spoffy commented on build/run.py
> +        return print(f"Failed to create symlink from '{mpmissions_dir / mission_output_dir}' to '{config.mission_output_path}'")
Can I suggest we re-throw with a generic exception instead of just returning? That way if something goes wrong, we don't go ahead and still start Arma, which might a nuisance.

2023-01-03 23:44 UTC, Spoffy commented on build/run.py
> +    try_update_arma_server_config(mission_name)
Similarly here, maybe `setup_temporary_arma_server_config`? We can also drop the `try` I think, as if this throws an OS error we abort the whole script (it doesn't fail gracefully)

2023-01-03 23:44 UTC, Spoffy commented on build/run.py
> +        f"-config={config.arma_server_config_path.with_suffix('.tmp')}",
Maybe we could use a return value from `setup_temporary_arma_server_config`?

2023-01-03 23:44 UTC, Spoffy commented on build/run.py
> +        server_config = server_config.replace("MISSION_NAME", mission_name)
I like this bit, setting it up dynamically with the mission name.

2023-01-03 23:46 UTC, Spoffy commented on build/arma_server.example.hpp
> +persistent = 0;
Would persistent=1 be a better option here, to make it easier to test things like JIP issues?

2023-01-14 17:39 UTC, veteran29 commented on build/arma_server.example.hpp
> +persistent = 0;
Agreed

2023-01-14 17:46 UTC, veteran29 commented on build/config.example.py
> +paradigm_path = config_dir.parent /  "paradigm"
I think the old example config had an error, `Path(__file__).parent` throws an error.
```
config_dir = Path(__file__).parent // build dir with build configs
config_dir.parent // repo root
```

2023-01-14 17:53 UTC, veteran29 commented on build/run.py
> +    try_update_arma_server_config(mission_name)
Agreed

2023-01-16 02:37 UTC, Spoffy commented on build/config.example.py
> +paradigm_path = config_dir.parent /  "paradigm"
Ah, you're right now I look at the path. `parent` would be `build`, so `parent.parent` would be repo root.

2023-01-16 02:39 UTC, Spoffy approved these changes

2023-01-16 02:51 UTC, merged