Director - Broadcast mission groups creation to participating players
Savage-Game-Design/Across-the-Fence pull request #120
Opened 2024-03-01 02:40 UTC by veteran29

- title
- JIP handling for client-side monitoring (from TODO)

2024-03-01 14:55 UTC, Spoffy requested changes

2024-03-01 14:55 UTC, Spoffy commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    _args params ["_playerId", "_missionId"];
Is this getting the correct args?

2024-03-01 14:55 UTC, Spoffy commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    ["vgm_mission_director_squadCreated", _mission get "director" get "aiGroups", _machineId] call para_g_fnc_event_triggerTargets;
At some point, I think I'd like this to be closer to the other place the event is emitted. Having it in a separate handler + file I think obscures the behaviour of `squadCreated` (i.e, when the event is triggered).

Right now, I'm wondering if something like:
```
[
   _codeToCallNow,
   _codeToCallOnJIP,
   _jipEventID
] call vgm_s_fnc_mission_triggerEvent
```
Would be a useful function to have. 
Or
```
[
   _jipID,
   _code
] call vgm_s_fnc_mission_onJip
```
...But I'm not sure yet. I think it's probably too early to refactor into the right patterns, so I'm inclined to leave it for now? :)

2024-03-01 14:55 UTC, Spoffy commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +}]] call para_g_fnc_event_subscribeLocal;
Could we register this in `preInit`? It feels like we don't need to register this on a per-mission basis, since we've got access to the director data through `_mission get "director"`. 

What do you think?

2024-03-01 15:04 UTC, Spoffy commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    ["vgm_mission_director_squadCreated", _mission get "director" get "aiGroups", _machineId] call para_g_fnc_event_triggerTargets;
Thinking about this more - I don't think we should send `squadCreated`  on JIP,  as the events are occurring in different contexts.

I think I'd prefer a separate event, `initialDirectorData` or `initialSquadData`  or `jipSquadData`, to distinguish the JIP case from the "I'm already on a mission and a new squad spawns" situation. It gives us more power on the client to do extra things for JIP.

2024-03-01 17:52 UTC, veteran29 commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    _args params ["_playerId", "_missionId"];
I think so? I've tested it by JIP attaching the player via console and it worked properly.

Event is fired with:
```sqf
["vgm_mission_attached", [_playerId, _missionPublic get "id"]] call para_g_fnc_event_triggerGlobal;
```
Event system does:
```sqf
[_this param [DATA_PARAMETER_INDEX], _savedParameters, _eventName, _topic, _originMachineId] call _code;
```

2024-03-01 18:41 UTC, veteran29 commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    ["vgm_mission_director_squadCreated", _mission get "director" get "aiGroups", _machineId] call para_g_fnc_event_triggerTargets;
Something like `vgm_s_fnc_mission_onJip` would work, we can easily refactor this if needed.

2024-03-01 18:43 UTC, veteran29 commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    ["vgm_mission_director_squadCreated", _mission get "director" get "aiGroups", _machineId] call para_g_fnc_event_triggerTargets;
Changed the JIP event to `vgm_mission_director_jipData` to have it separate.

2024-03-02 18:23 UTC, Spoffy commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    _args params ["_playerId", "_missionId"];
Re-read this today, and realised I'm just being an idiot. I mixed up the event `_args` with the saved parameters that get passed to the function (`_mission`). 

I usually use `_eventData` instead of `_args`, which I think is where the confusion came from :D

2024-03-02 18:29 UTC, Spoffy commented on game/functions/systems/mission_director/server/fn_director_startMission.sqf
> +    ["vgm_mission_director_squadCreated", _mission get "director" get "aiGroups", _machineId] call para_g_fnc_event_triggerTargets;
Perfect, thanks :D

2024-03-02 18:30 UTC, Spoffy approved these changes

2024-03-04 18:29 UTC, merged