Missions selection - Add zone reservation and modifiers system
Savage-Game-Design/Across-the-Fence pull request #131
Opened 2024-04-04 21:33 UTC by veteran29

- title

2024-05-18 18:06 UTC, Spoffy requested changes

2024-05-18 18:06 UTC, Spoffy commented on game/functions/systems/missions_zones/server/fn_missions_zones_freeZone.sqf
> +    File: fn_missions_selection_freeZone.sqf
Old folder name

2024-05-18 18:06 UTC, Spoffy commented on game/functions/systems/missions_zones/client/remoteExec/fn_missions_zones_remoteExec_receiveList.sqf
With this "fetch list" and "receive list" approach - I wonder if we should just keep the client updated with zone info at all times via a netmap (or similar). It won't change often, and might make the logic here simpler?

2024-05-18 18:06 UTC, Spoffy commented on game/functions/systems/missions_zones/server/fn_missions_zones_reserveZone.sqf
> +[_zoneReservationNetmap, _targetZone, _playerId] call para_s_fnc_netmap_set;
I wonder if zones should be reserved by a group, in case the mission leader quits or is disconnected?

If we do that, we'll also need to free up the reservation if the group is empty or deleted.

2024-05-18 18:06 UTC, Spoffy commented on game/functions/systems/missions_zones/server/fn_missions_zones_reserveZone.sqf
> +[_zoneReservationNetmap, _targetZone, _playerId] call para_s_fnc_netmap_set;
Alternatively we could have a "isZoneReserved" function that does all these checks? Might be simpler than handling the edge cases with all the additional event handlers.

2024-06-14 13:54 UTC, veteran29 commented on game/functions/systems/missions_zones/server/fn_missions_zones_reserveZone.sqf
> +[_zoneReservationNetmap, _targetZone, _playerId] call para_s_fnc_netmap_set;
I think it's fine as is for now, player ID does change if you do a full reconnect, leader leaving is not an issue as the zone is auto freed when mission is terminated.

2024-06-14 14:00 UTC, veteran29 commented on game/functions/systems/missions_zones/client/remoteExec/fn_missions_zones_remoteExec_receiveList.sqf
In general, I agree but in this particular case it's using these functions to prompt the eventual regeneration of the zone modifiers in the [getList](https://github.com/Savage-Game-Design/Across-the-Fence/pull/131/files#diff-b661f09cfdfccd3964fab0851b84a69c72039343ec4a5d9aa4ae27aa1b5aea81R38) function. 

I think this should be revised once we'll start implementing the "alive" zones that change after every mission.

2024-06-15 04:26 UTC, Spoffy commented on game/functions/systems/missions_zones/server/fn_missions_zones_reserveZone.sqf
> +[_zoneReservationNetmap, _targetZone, _playerId] call para_s_fnc_netmap_set;
Alright, let's merge for now, and we'll revisit when we get better mission/group management mechanics!

2024-06-15 04:26 UTC, merged