Rewrites Paradigm's keyhandler
Savage-Game-Design/Across-the-Fence pull request #133
Opened 2024-05-11 00:40 UTC by Spoffy

This PR:
* Rewrites paradigm's keyhandler system, and expands it to work correctly when displays are opened by the gamemode.
* Converts the skill system to use keyhandler.
* Adds the keybinding menu to VGM

2024-06-13 17:42 UTC, veteran29 requested changes

2024-06-13 17:42 UTC, veteran29 commented on paradigm/client/functions/keyhandler/fn_keyhandler_registerAction.sqf
> +    Public: No
This looks like it should be used by other modules.
```suggestion
    Public: Yes
```

2024-06-13 17:42 UTC, veteran29 commented on paradigm/client/functions/keyhandler/fn_keyhandler_registerAction.sqf
> +params ["_action"];
If this is supposed to be a public API I would add type check to params.
```suggestion
params [["_action", createHashmap]];
```

2024-06-13 17:42 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_preInit.sqf
> +        ["name", "OpenMedicalMenu"],
Name is used as a key in profile namespace save data. IMO should be prefixed.
```suggestion
        ["name", "vgm_OpenMedicalMenu"],
```

2024-06-13 17:42 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_preInit.sqf
> +["OpenMedicalMenu", vgm_c_fnc_medical_openMedicalMenu] call para_c_fnc_keyhandler_addGeneralActionHandler;
Goes with above suggestion.
```suggestion
["vgm_OpenMedicalMenu", vgm_c_fnc_medical_openMedicalMenu] call para_c_fnc_keyhandler_addGeneralActionHandler;
```

2024-06-13 17:42 UTC, veteran29 commented on paradigm/client/functions/keyhandler/fn_keyhandler_addDisplayActionHandler.sqf
> +        ["MyAction", para_c_fnc_doThing] call para_c_fnc_keyhandler_addGeneralActionHandler;
Invalid example

2024-06-13 17:42 UTC, veteran29 commented on paradigm/client/functions/keyhandler/fn_keyhandler_enableGeneralActionTriggeringOnDisplay.sqf
> + */
Not feeling the purpose of this function, it only forwards the call to `hookDisplayKeyEvents`.

2024-06-13 17:42 UTC, veteran29 commented on paradigm/client/functions/keyhandler/fn_keyhandler_getAllKeybinds.sqf
> +} forEach (profileNamespace getVariable "para_c_keyhandler_bindings");
Is the storage format different for new system than in the old one? If so I would rename the `para_c_keyhandler_bindings` or add v2 suffix so it does not break if people play this and mikeforce.

2024-06-14 00:58 UTC, Spoffy commented on paradigm/client/functions/keyhandler/fn_keyhandler_enableGeneralActionTriggeringOnDisplay.sqf
> + */
The main purpose of this function is to avoid having to remember how to do this when working on new displays in the future - even if "this" is just enabling a variable and making the display aware of key events.

As side benefits it gives us:
- 1 function to search for when looking for "global keybind aware" displays.
- A single point to refactor if we need to change this behaviour in the future.

2024-06-14 15:03 UTC, Spoffy commented on paradigm/client/functions/keyhandler/fn_keyhandler_getAllKeybinds.sqf
> +} forEach (profileNamespace getVariable "para_c_keyhandler_bindings");
Didn't even realise I'd used the same variable, amazing catch!

2024-06-14 15:47 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_preInit.sqf
> +        ["name", "OpenMedicalMenu"],
Mitigated this by prefixing the profile namespace key instead on a per-gamemode basis, so each gamemode has its own hashmap.

2024-07-04 14:33 UTC, veteran29 commented on paradigm/client/functions/keyhandler/fn_keyhandler_init.sqf
> +para_c_keyhandler_gamemodeId = _gamemodeId;
I would add an error/warning here in case it's double initialized:
```suggestion
if (!isNil "para_c_keyhandler_gamemodeId") then {
    ["ERROR", format ["Keybinding system was already initialized: %1", _gamemodeId]] call para_g_fnc_log;
};

para_c_keyhandler_gamemodeId = _gamemodeId;
```

2024-07-04 14:42 UTC, veteran29 approved these changes

2024-07-04 15:58 UTC, merged