Missions - On demand extraction
Savage-Game-Design/Across-the-Fence pull request #134
Opened 2024-05-24 17:38 UTC by veteran29

- title
- Requires RTO or radio object nearby

2024-05-25 18:48 UTC, Spoffy requested changes

2024-05-25 18:48 UTC, Spoffy commented on game/functions/systems/missions/client/fn_missions_preInit.sqf
> +}] call para_g_fnc_event_subscribeLocal;
What do you think to doing this in the mission framework's `startDeploy` function instead, and save ourselves adding extra events here, since we're in the same system?

2024-05-25 18:48 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/extraction/fn_missions_gameplay_extraction_addAction.sqf
> +    };
I wonder if this could be made to:
* Not scan all entities nearby
* Prioritise player radios
* Include emergency radio on the player

```sqf
private _radioObj = objNull;

if (backpack player in vgm_missions_gameplay_extraction_backpackRadios || player getSlotItem 611 isNotEqualTo "") then {
    _radioObj = player;
};

if (isNull _radioObj) then {
    private _squadmates = units group player;
    private _squadmateIdx = _squadmates findIf { player distance2D _x < 30 && backpack _x in vgm_missions_gameplay_extraction_radioBackpacks };
    if (_squadmateIdx > -1) then {
        _radioObj = _squadmates select 0;
    };
};

if (isNull _radioObj) then {
    private _nearbyRadios = _target nearEntities [ vgm_missions_gameplay_extraction_radioObjects ];
    if (count _nearbyRadios > 0) then {
         _radioObj = _nearbyRadios select 0;
    };
};

```

Note: I split radios into backpack radios and physical radio objects in the world, as separate arrays.

2024-05-25 18:48 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/extraction/fn_missions_gameplay_extraction_addAction.sqf
> +        vgm_mission_onMission
What do you think to adding/removing this action when the player deploys/end of mission, instead of adding it at postInit and checking this var? 

Not sure if there's notable upsides/downsides to either.

2024-05-25 18:48 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/fn_missions_gameplay_postInit.sqf
> +];
As  mentioned in the other comment, could we benefit from splitting this out into backpacks and world-radios? Will this also detect dropped backpacks?

2024-06-09 19:18 UTC, veteran29 commented on game/functions/systems/missions_gameplay/client/extraction/fn_missions_gameplay_extraction_addAction.sqf
> +        vgm_mission_onMission
Bools check is negligible in performance cost and adding and removing the condition is more code.

2024-06-13 02:08 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/extraction/fn_missions_gameplay_extraction_addAction.sqf
> +        vgm_mission_onMission
In that case, sounds fine to me :)

2024-06-13 02:09 UTC, Spoffy approved these changes

2024-06-13 13:36 UTC, merged