Locations 1 - Basic site spawning and management
Savage-Game-Design/Across-the-Fence pull request #135
Opened 2024-05-25 17:45 UTC by Spoffy

2024-07-05 19:23 UTC, veteran29 requested changes

2024-07-05 19:23 UTC, veteran29 commented on game/functions/systems/behaviour_trees/nodes/global/fn_btree_decorator_isInCombat.sqf
> +/*
Does not look like this file belongs in this PR.

2024-07-05 19:23 UTC, veteran29 commented on game/functions/systems/missions/client/internal/NOTES.txt
> +(Done) create
This seems random too.

2024-07-05 19:23 UTC, veteran29 commented on game/functions/systems/sites/server/fn_sites_addSiteType.sqf
> +        [_mySite] call vgm_s_fnc_sites_addSiteType;
Example does not match function signature/usage.

2024-07-05 19:23 UTC, veteran29 commented on game/functions/systems/sites/server/fn_sites_preInit.sqf
> +
```suggestion

if (!isServer) exitWith {};

```

2024-07-05 19:23 UTC, veteran29 commented on game/functions/systems/sites/server/fn_sites_postInit.sqf
> +
```suggestion
if (!isServer) exitWith {};

```

2024-07-05 19:23 UTC, veteran29 commented on game/functions/functions_server.hpp
> +    class site_types
Not 100% fond of the name, I feel like `site_templates` or `site_configs` would reflect better the purpose of these.

2024-07-27 00:16 UTC, Spoffy commented on game/functions/functions_server.hpp
> +    class site_types
I'll refactor this another PR, it'd cause annoying conflicts to do it in this one at this point! Happy with site_templates

2024-07-28 18:40 UTC, veteran29 approved these changes
LGTM

2024-08-01 02:09 UTC, merged