Get profile and save function for players #30zubgc
Savage-Game-Design/Across-the-Fence pull request #14
Opened 2023-01-03 23:21 UTC by cerebral-314

2023-01-03 23:22 UTC, SavageGameDesign commented
Task linked: [CU-30zubgc Give players a personal save](https://app.clickup.com/t/30zubgc)

2023-01-04 00:09 UTC, Spoffy requested changes

2023-01-04 00:09 UTC, Spoffy commented on game/functions/core/server/player/fn_player_get_profile.sqf
> +    [_profile] call vgm_s_fnc_player_save;
I think I'd expect `vgm_s_fnc_player_save` to accept a player as a parameter, and save them. Having to pass in the profile, means whenever want to save the player, we'll probably end up doing something like:

```sqf
private _profile = player getVariable "vgm_player_profile";
if (isNil "_profile") exitWith {};
[_profile] call vgm_s_fnc_player_save
```

I think it should probably be:
```sqf
[_player] call vgm_s_fnc_player_save;
```

And just create a new hashmap, populate it with relevant info, and then save it to the DB. At least for now :)

2023-01-04 00:09 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +["player", getPlayerUID player, _playerProfile] call vgm_s_fnc_db_typed_save;
This won't work as it's being run on the server, so `player` won't be the player to save :). But see my comment above first before mamiing any changes here anyway!

2023-01-04 00:09 UTC, Spoffy commented on game/functions/functions_server.hpp
> +        class player_get_profile {};
I think using the word 'profile' is going to get confusing here, since the term `player profile` already refers to their local profile file.

Maybe just `fetch_save` would be good. I prefer `fetch` over `get` as I think `fetch` implies doing more work than just returning a variable, such as accessing the DB!
// Think about appropriate naming/functionality for a player save system

2023-01-05 23:24 UTC, Spoffy requested changes

2023-01-05 23:24 UTC, Spoffy commented on game/functions/core/server/db/fn_db_get.sqf
> +_result
Let's add the deep copy here (`+_result`)

2023-01-05 23:24 UTC, Spoffy commented on game/functions/core/server/player/fn_player_fetch.sqf
> +    File: fn_player_get_fetch.sqf
The file name here isn't consistent with the actual file name :)

2023-01-05 23:24 UTC, Spoffy commented on game/functions/core/server/player/fn_player_fetch.sqf
> +    [_player] call vgm_s_fnc_player_save;
I don't think we should be doing two saves here.
We do a save - then set some properties, then do a save.
It feels like we should just invoke `[_player] call vgm_s_fnc_player_save`, which creates the save if it doesn't exist and returns it.

My reasoning is that we have double the number of saves, and we also have two places that are writing to the "save format" for players, which makes it easy to introduce inconsistencies.

2023-01-05 23:24 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
I don't think we need to fetch the profile from storage here. I think the safest thing to do is regenerate the save from scratch. That way we're not worrying about old data, or the existence/non-existence of the save.

What do you think?

2023-01-05 23:29 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_get.sqf
> +_result
Will do!

2023-01-05 23:29 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_fetch.sqf
> +    File: fn_player_get_fetch.sqf
Thanks for the spot

2023-01-05 23:41 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_fetch.sqf
> +    [_player] call vgm_s_fnc_player_save;
Thanks for the spot on this too... not entirely sure what my thought process was.

2023-01-06 00:00 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
To be honest this save function is really awkward... The reason I had this function originally take a profile as a parameter was due to this. It'd allow the programmer to fetch the profile do their changes and then save it to the database.

2023-01-06 01:08 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
My main thinking here is by having all the save code in one place, it avoids the code that modifies the profile object being spread throughout the codebase. It keeps things isolated, so we don't get ourselves into bug or refactoring hell later when one bit of the codebase touches a bit of the profile it shouldn't! 

In my mind, this function collects all the data associated with the player from the gamemode, and then stores it - which keeps all that modification to one file and gives us some abstraction. 

Which aspect of the save function is making you feel awkward? If we can get to the bottom of that, it might help improve the save system :)

2023-01-06 01:10 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
When we make deep copies of the hash maps we're no longer keeping all the save code in one place. That's what made me wanna trash the save function to begin with since hashmaps "save" when using the set function.

2023-01-06 01:21 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
> When we make deep copies of the hash maps we're no longer keeping all the save code in one place

Can you explain this one a little more? 🙂

2023-01-06 03:22 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
Currently the main database hash-map is stored on the missionProfileNamespace. Hash maps are essentially pointers to their objects. 

At the moment if we make a change to the database it all edits 1 place in memory. Which is what I think you want... however if you have me deep copy the hash-map every time I'm allocating another portion in memory that as you say we will have to maintain. 

Sorry for the run on sentence; it's kind of hard to explain. I can explain this with code if need be. A demonstration would be real easy to whip up.

2023-01-06 19:58 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
> another portion in memory that as you say we will have to maintain.
Ah, I think this might be where the misunderstanding is happening. I'm proposing we deep copy in db_get, then return the deep copy. We use the returned deep copy in a read-only way to populate the right systems, then throw that copy away.

I'm not proposing keeping that copy around long-term. My reason for deep copying is it protects us from accidental changes to the original copy, *and* gives us the same behaviour we'd see when working with a database (a copy of the data, where modifying it doesn't affect source data)

2023-01-06 20:00 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
In essence, we do:

1. db_get (retrieve raw data from db)
2. player_fetch (load player data into relevant parts of the gamemode). 

Once the data has been loaded into the various different bits of the gamemode, we de-allocate/forget about the data that was returned from the DB.

In other words, we effectively load the content from the DB, "de-serialize" it, and let player init continue?

2023-01-08 22:48 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_save.sqf
> +private _playerProfile = [_player] call vgm_s_fnc_player_fetch;
Okay I think I understand what you want... I'll whip it up real quick

2023-01-15 15:25 UTC, veteran29 requested changes

2023-01-15 15:25 UTC, veteran29 commented on game/functions/core/server/player/fn_player_save.sqf
> +private _savedData = ["player", getPlayerUID _player, _player] call vgm_s_fnc_db_typed_save;
Player object can't be saved to DB, it should be the HashMap.
```suggestion
private _savedData = ["player", getPlayerUID _player, _profile] call vgm_s_fnc_db_typed_save;
```

2023-01-15 15:25 UTC, veteran29 commented on game/functions/core/server/player/fn_player_save.sqf
> +_profile set ["uid", getPlayerUID _player];
I don't get this example. This function will always reset the "profile" to new hash, `private _profile = createHashMap;`

2023-01-15 15:25 UTC, veteran29 commented on game/functions/core/server/player/fn_player_save.sqf
> +            the missionNamespace object, but it's here just in case.
I don't get the meaning of this. If this is not required why even have it. Code is there to be used or not.

2023-01-16 02:33 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +_profile set ["uid", getPlayerUID _player];
This was my suggestion - we'll add extra lines in here for data when we need to persist things, whether they're stored on the player object, or in other systems, etc. 

So it'll create a new save, add the relevant data, then save it.

2023-01-16 02:36 UTC, Spoffy requested changes
Looking 99% of the way there to me now :)

2023-01-16 02:36 UTC, Spoffy commented on game/functions/core/server/player/fn_player_fetch.sqf
> +    File: fn_player_get_fetch.sqf
This still looks inconsistent? :D

2023-01-28 17:34 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_save.sqf
> +            the missionNamespace object, but it's here just in case.
With the change above this function will be required. I need to update that comment

2023-01-28 18:31 UTC, Spoffy commented on game/functions/core/server/player/fn_player_save.sqf
> +_profile set ["uid", getPlayerUID _player];
We'll use the provider system (scripted event handler wrapper) for this once i've implemented it

2023-01-28 18:32 UTC, Spoffy requested changes

2023-01-28 18:32 UTC, Spoffy commented on game/functions/core/server/player/fn_player_fetch.sqf
> +    File: fn_player_get_fetch.sqf
This is the last thing to fix for me :D

2023-01-28 18:33 UTC, cerebral-314 commented on game/functions/core/server/player/fn_player_fetch.sqf
> +    File: fn_player_get_fetch.sqf
Nice catch thank you :P

2023-01-28 18:35 UTC, Spoffy approved these changes

2023-01-29 20:52 UTC, veteran29 approved these changes
LGTM

2023-01-30 01:11 UTC, merged