Skill system framework #3918y7b
Savage-Game-Design/Across-the-Fence pull request #15
Opened 2023-01-29 15:11 UTC by veteran29

### Acceptance Criteria
- [x] A skill can be defined declaratively in a config or SQF file
- [x] A skill can be unlocked by purchasing one or more other skills (using AND or OR boolean logic) - Callback functions for skills unlocking
- [x] A skill can be manually unlocked by a script. (e.g, when a player completes a certain action or visits a certain location). This is persistent.
- [x] An entire skill tree can be unlocked by one or more skills (e.g, specialization and expertise trees)
- [x] A skill tree has a parent tree, which will be used in the UI to give it a hierarchy.
- [x] A skill tree has a name, and a description, which will be used in the UI.
- [x] A skill can be purchased by spending a skill point, giving the player its benefit.
- [x] A passive skill is made active as soon as it is purchased, and persists across missions and respawn.
- [x] An active skill is triggerable by the player. 
- [x] An active skill has a cooldown period after activation in which it cannot be used.
- [x] The cooldown period affects each type of skill individually.
    - [x] E.g - Activating the primary skill doesn't start the ultimate skill cooldown.
    - [x] E.g - Activating the primary skill then swapping it out, means the new skill is still on cooldown.
- [x] One primary skill may be usable at a time. 
- [x] One ultimate skill may be usable at a time.
- ~~The ultimate skill must be lockable via script to prevent it being changed (e.g, when on a mission)~~
    - Should be handled in UI, IMO - @veteran29
- [x] Skills may have a criteria, which if not met means they will be invisible in the UI. 
- [x] Skills have a description, which will be shown in the UI.
- [x] Skills have a short description, which will be shown in the UI.
- [x] Skills have a name, which is shown in the UI.
- [x] Skills have an icon, which is shown in the UI.
- [x] Skills must be associated with a skill tree

2023-01-29 15:11 UTC, SavageGameDesign commented
Task linked: [CU-3918y7b Skills framework](https://app.clickup.com/t/3918y7b)

2023-02-09 21:46 UTC, Spoffy requested changes
Phew, big PR! Left a bunch of feedback. I don't think there's major or system changing, just lots of little tweaks and a few bits of added functionality.

The biggest thing I think we need to add is unlearning skills. I forgot to spec it out in the original ticket I think ☹️

2023-02-09 21:46 UTC, Spoffy commented on game/configs/mission/cfg_skills.hpp
> +    codeActivate = "systemChat 'skill activated'";
I think we'll need a hook for deactivating too, in case someone changes their skills

2023-02-09 21:46 UTC, Spoffy commented on game/configs/mission/cfg_skills.hpp
> +    codeActivate = "systemChat 'skill activated'";
We'll also need a cooldown property, for the delay between activations

2023-02-09 21:46 UTC, Spoffy commented on game/functions/functions_client.hpp
> +        class skills_treesHashToPathsHash;
I like your functions names, feels like I can intuit what these do easily enough.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/functions_client.hpp
>          };
Can we call this preinit from the main skills one? It feels like active skills shouldn't be initialising separately from the rest of the skills system?

I think it makes it confusing for someone to deduce how the init process works. If they're reading the main init file to understand the system, they need to:
1.  Realise there's two init files
2.  Realise they're both configured in the functions config
3.  Understand that the load order is defined by the order in this file, which I don't think is common knowledge.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/functions_server.hpp
> +    };
Nicely organised, I like your folder structure for the skills system.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_teachSkill.sqf
> +        _skillPath - Path to the skill being teched [ARRAY]
I think it should be `taught` here instead of `teached` :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +private _hash = _player getVariable "vgm_g_skillsData";
By _hash, do you mean a skills hash table? As this confused me for a minute, I thought we were passing around some kind of `hashValue _skills` or similar :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +};
I think we should load player skills from the DB separately, rather than load it here.

My thinking is:
* If we move to an actual DB in the future, this would potentially be a blocking function (or we'd need to rewrite the db layer to have async options). Which would mean this whole function has a fast path, and a slow path, and we wouldn't know which we'd hit when calling it.
* It pulls from a cache, which I wouldn't have expected based on the name - I'd have expected a db fetch each time.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +_hash getOrDefault ["skillPaths" , [], true];
What do you think to using `_hash set ["skillPoints", 0, true]`, to be a bit a little clearer about what this operation is doing, since we're not using the value it returns?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +    _player setVariable ["vgm_g_skillsData", _hash];
Will there be a runtime error if there's no skills data in the database? Specifically when we hit the `getOrDefault` lines below

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbSave.sqf
> +};
Where is the skills data structure initially set on new players? As I can't see dbGet or dbSet handling it, and I can't find the init code elsewhere, but I very well could just be missing it.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbSave.sqf
> +saveMissionProfileNamespace // return
I think this shouldn't a concern of the skills system, feels like this should be transparently handled by the db system, as we shouldn't need to care about the backend saving implementation.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbSave.sqf
> +private _hash = _player call vgm_s_fnc_skills_dbGet;
Similar comment to above about naming, I wonder if we should use `_skillsHashMap` or `_playerSkills` or similar?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_teachSkill.sqf
> +    File: fn_skills_teachSkill.sqf
I can't find any calls to this function - is it just a utility function for debugging?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    if (_skill getOrDefault ["_known", false]) then {
Why do we use `_` at the start of this hashmap property here?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    _skill set ["_known", true];
When the player receives skill data, I don't think we roll back their old skills data? So for example, if we un-taught a skill on the server, it would always be set as known on the client.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    ["vgm_skills_learnt", [_x, _skill]] call para_g_fnc_event_trigger;
If this is called whenever we learn a skill, for every skill, I think that means the `apply` code for each skill would need to be idempotent? 

For example, it couldn't be `player setCustomAimCoef (getCustomAimCoef player + 1)`, every time a player learned a different skill it'd give them the bonus for that skill again.

I think this poses some interesting challenges, such as multiple skills which modify the same thing on the player, but not unsolvable ones.

There's three options I think we could take here:
* Only apply newly learned skills
* Remove all skills, and re-apply them all.
* Add documentation to the skills config that `apply` needs to be idempotent, and explain the consequences.

Given idempotency can be quite a nice property (it'll reduce bugs most likely, although increasing complexity), I'd be keen to hear what you think.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/network/fn_skills_handle_skillLearnRequest.sqf
> +params ["_player", "_skillPath"];
Do we need to do `owner _player isEqualTo remoteExecutedOwner` for security here?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/global/fn_skills_preInit.sqf
> +vgm_skills_pathsHash = [vgm_skills_treesHash] call vgm_g_fnc_skills_treesHashToPathsHash;
I like that you've cached these in hashmaps, great idea. Wonder if we should add "map" to the end of "Hash" to make it clear we've got a map?

2023-02-09 21:46 UTC, Spoffy commented on game/configs/mission/cfg_skills.hpp
> +    isActive = 0; // 1 - primary skill, 2 - ultimate skill
Can we use `skillType` or similar for this? Since this is prefixed with `is`, I think I'd expect it to be a boolean value

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/global/fn_skills_parseTreeCfg.sqf
> +                ["codeActivate", compileFinal getText (_x >> "codeActivate")]
Does compileFinal work in hashmaps? This isn't feedback, I'm just curious :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/fn_skills_getSkillTreeFromSkill.sqf
> +    if (count _path == 1) exitWith {
Can we do `<= 1` here? 

On the happy path where everything works, it'll behave the same.

On the unhappy path (where path ends up as 0, if we *somehow* have bad data in skill), it prevents an infinite loop.

Not exactly a likely issue, but it's a little bit more defensive :)

Can add a comment why it's `<=` for clarity too.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/fn_skills_getSkillPoints.sqf
> +    File: fn_skills_getSkillPoints.sqf
To be 100% clear, is this the skill points the player has left to spend, and not their total?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_openSkillWheel.sqf
> +[_iconsArray] call vn_fnc_wm_init;
We've got a wrapper around the native wheel menu here, that might be easier to use, and has some convenience functions (such as loading a wheel menu interface from config)
paradigm\client\functions\ui\wheel_menu\fn_wheel_menu_open.sqf

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_preInit.sqf
> +}];
Short term, all good with this.

Long term, we should integrate the keybindings menu from MF, or use Arma's builtin one. I'll open a dev ticket for it.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_preInit.sqf
> +}] call para_g_fnc_event_subscribeLocal;
We'll need to handle unlearning here too.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_isSlotOnCooldown.sqf
> +time < (_slot getOrDefault ["cooldown", 1e10]) // return
I'd have expected cooldown to be "how long this takes to cooldown" from the name, such as 60 seconds, or 20 seconds remaining.

Maybe we could use "nextAvailableTime" or "cooldownEndTime" to be clearer :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_skillWheelActivate.sqf
> +private _cooldown = time + ([30, 60] select (_skill get "isUltimate"));
Same as the config comment, it'd be good to have this as a per-skill setting :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/global/fn_skills_parseTreeCfg.sqf
> +                ["cost", 1],
Good thinking, can we pull this out into the config too? :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_addSkillPoint.sqf
> +};
Wonder if we could/should add a skill point without re-broadcasting all the skills data? As I think this will trigger them all to be re-learned, etc.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/global/fn_skills_canLearn.sqf
> +        diag_log [_skillTree get "displayName", count (_skillTree get "skills")];
Rogue diag_log. Maybe we put it as a debug log, or cut it? :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/global/fn_skills_canLearn.sqf
> +        _path = _path select [0, count _path - 2];
Could we put a comment in here, explaining we're selecting the skill's tree's parent tree? :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/global/fn_skills_canLearn.sqf
> +        private _skillTree = _path call vgm_g_fnc_skills_getByPath;
Same here, maybe we rename this to `parentSkillTree` or similar for clarity :)

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_addSkillPoint.sqf
> +_skillsData set ["skillPoints", _skillPoints + 1];
Is there a missing skills_dbSave here?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/network/fn_skills_handle_skillLearnRequest.sqf
> +_skillsData set ["skillPoints", _skillPoints - 1];
this is currently -1, I think we should be grabbing the skill's cost?

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_addSkillPoint.sqf
> +params ["_player", ["_broadcast", false]];
What's the situation where not sync'ing this with the client would help us?  I'm a little concerned the default settings here might lead to us accidentally de-syncing the skills from the client.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/network/fn_skills_handle_skillLearnRequest.sqf
> +["SUCCESS", format ["VGM: Handling learn request for %1 (%2), %3", name _player, getPlayeRUID _player, _skillPath]] call para_g_fnc_log;
We probably want to use "INFO" or "DEBUG", as I don't think "SUCCESS" is one of the standard (undocumented) log levels. I'll push to paradigm later with the header updated with a list of log levels.

2023-02-09 21:46 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_teachSkill.sqf
> +[_skillsData] remoteExecCall ["vgm_c_fnc_skills_receiveSkillsData", _player];
Feels like this duplicates handle_skillLearnRequest a lot. Maybe we should have handle_skillLearnRequest call this? (Wondering if that was your original plan, since this is unused currently)

2023-02-24 19:22 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_addSkillPoint.sqf
> +params ["_player", ["_broadcast", false]];
The idea was that it can be executed multiple times before broadcasting but it does not make sense, I've added `_amount` param instead if you want to add multiple skill points.

2023-02-24 19:56 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_teachSkill.sqf
> +[_skillsData] remoteExecCall ["vgm_c_fnc_skills_receiveSkillsData", _player];
Refactored it to use `teachSkill` in `skillLearnRequest`.

2023-02-24 19:56 UTC, veteran29 commented on game/functions/systems/skills/server/network/fn_skills_handle_skillLearnRequest.sqf
> +_skillsData set ["skillPoints", _skillPoints - 1];
Skill cost wasn't fully implemented, fixed.

2023-02-24 20:17 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +private _hash = _player getVariable "vgm_g_skillsData";
It's a hashMap

2023-02-24 20:21 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_teachSkill.sqf
> +    File: fn_skills_teachSkill.sqf
>A skill can be manually unlocked by a script. (e.g, when a player completes a certain action or visits a certain location). This is persistent.

API Func. Part of acceptance criteria.

2023-02-24 20:25 UTC, veteran29 commented on game/functions/systems/skills/global/fn_skills_parseTreeCfg.sqf
> +                ["codeActivate", compileFinal getText (_x >> "codeActivate")]
It does not, matter of habit.

2023-02-24 20:26 UTC, veteran29 commented on game/functions/systems/skills/client/fn_skills_getSkillPoints.sqf
> +    File: fn_skills_getSkillPoints.sqf
Current amount of skill points that player can spend.

2023-02-24 20:26 UTC, veteran29 commented on game/functions/systems/skills/client/active/fn_skills_active_openSkillWheel.sqf
> +[_iconsArray] call vn_fnc_wm_init;
Not a concern for this PR, it's a placeholder UI.

2023-02-24 20:27 UTC, veteran29 commented on game/functions/systems/skills/client/active/fn_skills_active_preInit.sqf
> +}];
Not a concern for this PR, it's a placeholder UI. Arma modded keybindings can only be used in Mods.

2023-02-24 20:33 UTC, veteran29 commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    ["vgm_skills_learnt", [_x, _skill]] call para_g_fnc_event_trigger;
This is not a concern.

Following applies due to `_known` check:
> Only apply newly learned skills

2023-02-24 20:34 UTC, veteran29 commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    if (_skill getOrDefault ["_known", false]) then {
The skillTrees hashmap is identical on every client by default and is kinda "locally global", properties that are not coming from config but are used locally are marked with `_`.

2023-02-24 20:39 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +    _player setVariable ["vgm_g_skillsData", _hash];
`db_get` always returns a HashMap.

2023-02-24 20:42 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +};
If not load it here then where?

The slow path is done only once and it will always happen when a player is joining the server.

The idea behind the cache is that the player can't play on multiple servers at once, so we can re-use the data without polling the DB all the time.

2023-02-24 20:43 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_dbSave.sqf
> +};
`dbGet` L26

2023-02-24 20:59 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +};
I'd load it on player join, before anything else happens, so that data is all there and waiting to be used.

In terms of cache - my point was more that I think the behaviour doesn't match the function name. I agree we should be caching it and not re-accessing the DB 🙂

2023-02-24 21:00 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +    _player setVariable ["vgm_g_skillsData", _hash];
Cool - you're absolutely right.

2023-02-24 21:01 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbSave.sqf
> +};
Aha, got it, it's a side-effect of the dbGet, I see that now. Thanks!

2023-02-24 21:02 UTC, Spoffy commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    if (_skill getOrDefault ["_known", false]) then {
Ah, got it. I think we need to document that somewhere, maybe in README.md in the skills system directory?

2023-02-24 21:04 UTC, Spoffy commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    ["vgm_skills_learnt", [_x, _skill]] call para_g_fnc_event_trigger;
Right, I didn't see that check! Thanks :)

2023-02-25 02:33 UTC, gnalvesteffer commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +private _hash = _player getVariable "vgm_g_skillsData";
Would recommend naming this `_skillsData`. `_hash` just tells me the datatype (or really it should be `_hashMap` if you want to be accurate). Alternatively `_skillsHashMap`.

2023-02-25 02:36 UTC, gnalvesteffer commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +};
I obviously don't have all the context here, but I do agree with @Spoffy regarding loading all the data upfront from the DB when a player joins, and then caching it, where feasible. Potentially long-running, blocking operations would introduce hitching during play, which is undesirable.

2023-02-25 02:38 UTC, gnalvesteffer commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +        Something [BOOL]
Is this Return documentation accurate? Looks like it returns the skills data for the player (hashmap).

2023-02-25 02:40 UTC, gnalvesteffer commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +};
Also with that in mind ^, this function could be renamed to `cacheGet` or similar.

2023-02-25 17:10 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +};
> I'd load it on player join, before anything else happens, so that data is all there and waiting to be used.

Doesn't change much as first thing player does is call for this data == load it.

> I do agree with @Spoffy regarding loading all the data upfront from the DB when a player joins, and then caching it, where feasible. Potentially long-running, blocking operations would introduce hitching during play, which is undesirable.

It doesn't matter when we load the data if it's synchronous, loading it early during player connection will still freeze the server, unless we want to completely refactor the DB handling and make it async.


Anyways, is this good?: 0f7fa47d821f937268c97f9065482bfe15cefe9a

2023-02-25 17:16 UTC, veteran29 commented on game/functions/systems/skills/server/network/fn_skills_handle_skillLearnRequest.sqf
> +params ["_player", "_skillPath"];
Not sure if we need it but added.

2023-02-25 17:28 UTC, veteran29 commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    if (_skill getOrDefault ["_known", false]) then {
Not relevant anymore, the list of already applied skills will be kept in an array.

2023-02-25 17:45 UTC, gnalvesteffer commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +};
It should be async then, but it may or may not be such a big deal, depending on how frequently players join and the max player count. To your point, it wouldn’t matter that much if we load on join or whenever needed, since the server would freeze all the same to the clients. Though loading all data upfront on join would reduce the amount of freezing throughout a playthrough (given we need to pull more data).

2023-02-26 18:15 UTC, veteran29 commented on game/functions/systems/skills/client/network/fn_skills_receiveSkillsData.sqf
> +    _skill set ["_known", true];
Added handling of forgotten skills with skill respec.

2023-02-26 18:15 UTC, veteran29 commented on game/functions/systems/skills/client/active/fn_skills_active_preInit.sqf
> +}] call para_g_fnc_event_subscribeLocal;
Added handling of forgotten skills with skill respec.

2023-02-26 22:13 UTC, Spoffy approved these changes

2023-03-03 00:40 UTC, Spoffy approved these changes

2023-03-03 00:40 UTC, Spoffy commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +    File: fn_skills_dbSave.sqf
Header needs an update :)

2023-03-03 01:31 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_dbGet.sqf
> +    File: fn_skills_dbSave.sqf
```suggestion
    File: fn_skills_dbGet.sqf
```

2023-03-03 01:34 UTC, merged