Scouting - Add scouting system
Savage-Game-Design/Across-the-Fence pull request #161
Opened 2024-08-24 02:33 UTC by veteran29

- title

2024-08-24 19:35 UTC, veteran29 commented
After the playtest will be reworked for manual site type and grid input.

2024-10-24 23:50 UTC, Spoffy requested changes

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/sites/server/fn_sites_spawn.sqf
> +["vgm_sites_siteSpawned", [_site]] call para_g_fnc_event_triggerServer;
Since this is a server function, we could use `triggerLocal` which would be more efficient, as it avoids the remoteExec call.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/core/client/displays/fn_displayNotepad.sqf
> +        };
Do we want to hide this behind a __A3_DEBUG__ or some setting that can be enabled at runtime? Otherwise can we remove it or comment it out?

2024-10-24 23:50 UTC, Spoffy commented on game/functions/core/client/displays/fn_displayNotepad.sqf
> +        _ctrlHeader ctrlSetText toUpper "Scouting report";
String needing localizing?

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/sites/server/fn_sites_spawn.sqf
> +    ["class", _typeId],
I feel like "class" might be a bit broad of a name. We could just use "icon" perhaps? Depends how you're thinking we should use this in the future.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_createSystemNetmap.sqf
> +        _missionId - Id of the missin to get the netmap from [NUMBER]
```suggestion
        _missionId - Id of the mission to get the netmap from [NUMBER]
```

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_getSystemNetmap.sqf
Should we make this a global function? Since we're using netmaps, it feels natural to make the mission's system netmaps available on the client via a nice function call.

Can use vn_c_fnc_getMissions for that (which actually should be global itself, since it will happily work globally)

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_startMission.sqf
> +(_mission get "sites") append _sites;
Rather than tracking this with the `sites` variable within the mission system, you can use vgm_s_fnc_missions_zones_getSites to fetch the sites.

That's because sites are more closely connected to a zone rather than a specific mission (they'll be semi-persistent in zones eventually).

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_createMission.sqf
> +    ["sites", []]
This can probably be removed, and `vgm_s_fnc_missions_zones_getSites` used instead (see a later comment)

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions/server/internal/fn_missions_calculateMilestones.sqf
> +    private _missionSites = +(_mission get "sites");
```suggestion
    private _missionSites = +((_mission get "public" get "targetZone") call vgm_s_fnc_missions_zones_getSites);
```

Can do something like this, and not track `sites` inside the mission.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions/server/internal/fn_missions_calculateMilestones.sqf
> +        private _nearSites = _missionSites select {SITE_DIST <= 200};
Might be worth switching to using `inAreaArrayIndexes` here, to prevent any performance hiccups in the future.

This select is currently quadratic in the number of sites, so 500 in the worst case right now (number_of_guessed_sites * number_of_sites), and number of guessed sites is capped at the number of sites.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions/server/internal/fn_missions_calculateMilestones.sqf
> +        };
I read this as:

```
If there is a site of the right type within 200m:
    Score 200, prevent this site from scoring again.
    
Else if there is a site of the wrong type within 200m:
    Score 100, prevent this site from scoring again.
```

One issue here is it means a good spot can prevent a perfect spot - if you spot a nearby site with the wrong type, and also spot correctly the site with the right type, there's a chance the good spot gets processed first.

I think that's okay for now - but could we add a comment explaining it, so we don't get caught out in the future?

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +};
An alternative here is to use `vgm_s_fnc_sites_getAllSiteTypes`, instead of reading from the config. They're initialised in preInit, so it would be fine to use here :)

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +}] call para_g_fnc_event_subscribeServer;
I love how cleanly this works with the event-driven approach.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/scouting/fn_missions_gameplay_scouting_onPhoto.sqf
> +        Something [BOOL]
Documentation 🙂

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/scouting/fn_missions_gameplay_scouting_getSiteById.sqf
We could make this global, if we made a couple of other netmap-related mission functions global (e,g "getSystemNetmap").

That would solve your "TODO - Make shared function" comments in most of the server's handlers for finding the guessed site.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_handleSpotted.sqf
> + */
Documentation 🙂

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +
Is this used? Couldn't find any code that emits this event.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_handleSpotted.sqf
> +    File: fn__missions_gameplay_scouting_handleSpotted.sqf
Is this still used? The event that calls this never seems to be triggered anywhere.

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_onMissionStarted.sqf
> + */
Docs :)

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +
Might want to monitor the performance of this - there could be a *lot* of objects here. There's also potentially other implementations of taking photos we can look into (such as raycasting + using the hit position, and comparing it to the site location. The locational events system would make this simple - register each site as a listener, and have a player taking a photo trigger a "photo taken" event at the raycast hit position with a radius of 50m or similar.)

2024-10-24 23:50 UTC, Spoffy commented on game/functions/systems/sites/server/fn_sites_spawn.sqf
> +["vgm_sites_siteSpawned", [_site]] call para_g_fnc_event_triggerServer;
We'll also need to move this onto the client once sites have local objects, or similar. That's going to be its own set of headaches - since you're reading the `objects` array, we'll need to figure out a way to add the local-only objects too.

2024-10-24 23:50 UTC, Spoffy commented on game/mission/stringtable.xml
>      </Package>
```suggestion
        <Key ID="STR_VGM_MISSION_END_UI_MILESTONE_SITE_SPOTTED_PERFECT">
            <Original>%1. Enemy site marked [Perfect]</Original>
        </Key>
        <Key ID="STR_VGM_MISSION_END_UI_MILESTONE_SITE_SPOTTED_GOOD">
            <Original>%1. Enemy site marked [Good]</Original>
        </Key>
        <Key ID="STR_VGM_MISSION_END_UI_MILESTONE_SITE_SPOTTED_BAD">
            <Original>%1. No enemy site at marked location.</Original>
        </Key>
    </Package>
```

2024-10-29 16:18 UTC, veteran29 commented on game/functions/systems/sites/server/fn_sites_spawn.sqf
> +["vgm_sites_siteSpawned", [_site]] call para_g_fnc_event_triggerServer;
Local objects can be stored separately as spawn ids, local objects framework supports init code which executes where it's spawned. So I don't think that'll be much of a problem. Minor changes might be needed.

2024-10-29 16:35 UTC, veteran29 commented on game/functions/systems/sites/server/fn_sites_spawn.sqf
> +    ["class", _typeId],
I don't think `icon` is good name either. the `_typeId` is literally mapped to class in the config so I think it's fitting.

2024-10-29 16:42 UTC, veteran29 commented on game/functions/systems/missions_gameplay/client/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +};
This is used on the client so that data is unavailable, I think unifying this should be a part of general refactor of how sites are stored.

2024-10-29 16:45 UTC, veteran29 commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +
The `setSpottable` function is pretty light so it shouldn't be too hard on performance and this happens only once upon mission start so should be ok.

2024-10-29 16:47 UTC, veteran29 commented on game/functions/systems/missions/server/fn_missions_getSystemNetmap.sqf
I guess we can refactor when needed? Or make client variant of the function?

2024-10-29 17:06 UTC, veteran29 commented on game/functions/core/client/displays/fn_displayNotepad.sqf
> +        };
Commented out

2024-10-29 17:06 UTC, veteran29 commented on game/functions/core/client/displays/fn_displayNotepad.sqf
> +        _ctrlHeader ctrlSetText toUpper "Scouting report";
Done

2024-10-30 02:43 UTC, veteran29 commented on game/functions/systems/missions/server/internal/fn_missions_calculateMilestones.sqf
> +        private _nearSites = _missionSites select {SITE_DIST <= 200};
`inAreaArrayIndexes` would indeed be fastest but I need to check the element `class` to check if it's a perfect spot. `inAreaArray` will still be faster than the select so I'll switch to that.

```sqf
sites = [];
sites resize 10000;
sites = sites apply {createHashMapFromArray [["pos", [random 1000, random 1000]]]};

_fnc_a = {
	_this select {(_x get "pos") distance [100, 100] < 200};
};

_fnc_b = {
	(_this apply {_x get "pos"}) inAreaArrayIndexes [[100, 100], 200, 200];
};

_fnc_c = {
	(_this apply {_x get "pos"}) inAreaArray [[100, 100], 200, 200];
};

[
	diag_codePerformance [_fnc_a, sites, 1000, true], // 5.45592 ms
	diag_codePerformance [_fnc_b, sites, 1000, true], // 1.04804 ms
	diag_codePerformance [_fnc_c, sites, 1000, true]  // 2.64881 ms
]
```

2024-10-30 18:02 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_getSystemNetmap.sqf
Yeah, sounds good - happy to refactor when needed.

2024-10-30 18:05 UTC, Spoffy commented on game/functions/systems/missions/server/internal/fn_missions_calculateMilestones.sqf
> +        private _nearSites = _missionSites select {SITE_DIST <= 200};
Perfect, thanks for interesting performance comparison too :D

2024-10-30 18:07 UTC, Spoffy commented on game/functions/systems/missions_gameplay/client/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +};
Sounds good to me 👍

2024-10-30 18:11 UTC, Spoffy commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +
Righto - we'll monitor this then! :)

2024-10-30 21:35 UTC, veteran29 commented on game/functions/systems/missions/server/internal/fn_missions_calculateMilestones.sqf
> +        private _nearSites = _missionSites select {SITE_DIST <= 200};
Used `inAreaArrayIndexes` in the end, was a bit tired and haven't noticed that `inAreaArray` will give me the same troubles so went with minor refactor and used the faster method.

2024-10-30 21:38 UTC, veteran29 commented on game/functions/systems/missions_gameplay/client/scouting/fn_missions_gameplay_scouting_getSiteById.sqf
I would like to tackle this in separate PR after hints will be done.

2024-10-30 21:39 UTC, veteran29 commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_handleSpotted.sqf
> + */
Removed the function, unused.

2024-10-30 21:40 UTC, veteran29 commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_handleSpotted.sqf
> +    File: fn__missions_gameplay_scouting_handleSpotted.sqf
It's a remnant from the time where scouting checked if you have "hit" the site while placing it on the map. Removed.

2024-10-30 21:42 UTC, veteran29 commented on game/functions/systems/missions_gameplay/server/scouting/fn_missions_gameplay_scouting_postInit.sqf
> +
Not used, removed.

2024-11-01 16:10 UTC, Spoffy approved these changes

2024-11-02 00:15 UTC, merged