Missions - Spawn random sites on mission start
Savage-Game-Design/Across-the-Fence pull request #162
Opened 2024-08-24 02:36 UTC by Spoffy

Enables random site spawning on mission start.

This currently just spawns the objects when the mission starts, and clears them up on mission end.

It doesn't change any AI spawning or behaviour.

There's also a few fixes in here for sites that were spawning underground.

2024-08-24 19:45 UTC, veteran29 requested changes

2024-08-24 19:45 UTC, veteran29 commented on game/functions/systems/missions_zones/server/fn_missions_zones_spawnRandomSites.sqf
> +    private _createdSite = [_chosenSiteId, _chosenLocation] call vgm_s_fnc_sites_spawn;
Won't this spawn the site in occupied location if it could not find free one? Making it two sites spawn in eachother.

2024-08-27 19:04 UTC, Spoffy commented on game/functions/systems/missions_zones/server/fn_missions_zones_spawnRandomSites.sqf
> +    private _createdSite = [_chosenSiteId, _chosenLocation] call vgm_s_fnc_sites_spawn;
.....Yes. :facepalm:

2024-08-29 02:06 UTC, Spoffy commented on game/functions/systems/missions_zones/server/fn_missions_zones_spawnRandomSites.sqf
> +    private _createdSite = [_chosenSiteId, _chosenLocation] call vgm_s_fnc_sites_spawn;
Fixed and pushed 🙂

2024-09-20 16:26 UTC, veteran29 approved these changes
LGTM

2024-09-29 15:25 UTC, merged