feat: Respawn System
Savage-Game-Design/Across-the-Fence pull request #17
Opened 2023-02-13 02:59 UTC by gnalvesteffer

**Description:**
Implements a respawn system according to the [ClickUp ticket](https://app.clickup.com/t/30zwkcc). I assume this is placeholder or a first-pass for a more in-depth system once more of the gamemode is implemented.

Additional efforts outside the ticket include:
- Screen fade transition on death
- Smarter spawn positioning that tries to put the player closer to the majority of their team, ignoring lonewolves and encouraging teamwork.
- Player's direction is oriented towards the group when respawned, giving them a natural guidance on where to go.

**Preview:**
https://medal.tv/games/arma-3/clips/V1GbCnqRlspdd/d1337ZO6XT7c?invite=cr-MSxNOG0sMTYyMzA2MjA1LA

**Acceptance Criteria**
- [x] When a player is killed, they should respawn within 300 to 500m from the team. 
- [x] The direction they spawn in should be random
- [x] They shouldn't spawn in within 100m of an enemy, unless a number of other attempts at spawning them in have been unsuccessful.
- [x] They shouldn't spawn in water.
- [ ] The enemy should no longer be aware of the respawned player **_(I'm not familiar with this, shouldn't the enemy already be unaware of a respawned player?)_**

2023-02-16 16:22 UTC, Spoffy requested changes
Really cool work - love the attention to detail with the fade effects, and error/edge case handling. 

Left a bunch of comments, but nothing major - mostly just performance or style suggestions. 🙂

2023-02-16 16:22 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    private _nearGroupMembers = (_unit nearEntities ["AllVehicles", LONEWOLF_DISTANCE]) select { group _x == _group && _x call _groupMemberPredicate};
We can rewrite this in a couple of ways, that'll make it a bit faster, particularly under edge cases. It's not really necessary given how rarely this is called, and the size of the group, but wanted to share in case you'd find it useful!

1) Use "Man" instead of "AllVehicles"
```sqf
_unit nearEntities ["Man", LONEWOLF_DISTANCE]
```
Will save you a little bit of filtering, and dealing with any random vehicles.

2)
```sqf
private _nearGroupMembers = _unitsInGroup inAreaArray  [getPos _unit, LONEWOLF_DISTANCE, LONEWOLF_DISTANCE] select _groupMemberPredicate
```
This has a few advantages: 
* Only loops through group members, so very tightly bounded.
* Avoids `call` inside `select`. The overhead of the extra call on every loop iteration is quite high, whereas using the predicate directly avoids this.

2023-02-16 16:22 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    };
Could always just track the highest value in a couple of variables, `private _largestGroup`, `private _largestGroupUnits`, to save yourself the hassle of finding the max later on :)

Do we need to do the `select` here? I think even if the `_unit` is included in the count, all we care about is the largest group, and it means all the counts will just be 1 larger?

2023-02-16 16:22 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +private _majorityUnits = _memberCountToMembers get (selectMax (keys _memberCountToMembers));
Not seen this before, interesting use of the hashmap keys :)

2023-02-16 16:22 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    _positionSum = _positionSum vectorAdd [_unitPosition#0, _unitPosition#1, 0];
Could just zero out the 3rd parameter at the end :)

2023-02-16 16:22 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    _unitCountSum = _unitCountSum + 1;
Shouldn't need to count this, think we can just do `count _majorityUnits` 🙂

2023-02-16 16:22 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_onPlayerKilled.sqf
> +[0, "WHITE", 3, 1] spawn BIS_fnc_fadeEffect;
I really really love that you've added this.

2023-02-16 16:22 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_getInitialSpawnPointMarkerTransform.sqf
> +    [getPosASL player, direction player]; // TODO: remove before merge -- this is only for testing!!!
Maybe leave this this in as a default behaviour, add an error log message *and* make it do a global `hint`, as this is ultimately a mission configuration error.

Just in case we forget to add or rename this marker and get confused :D

My other suggestion would be to throw an exception or doing something very loud to make the user aware, but Arma doesn't really have anything like that, except for deliberately causing script errors :(

2023-02-16 16:22 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +    private _safePosition = [_groupPositionASL, _minDistanceFromTeam, _maxDistanceFromTeam, 5, 0, 30, 0, [], [[0, 0], [0, 0]]] call BIS_fnc_findSafePos;
Generally, it's worth avoiding BIS functions because they're sloooooow. But I don't think this is an issue given the specificness of this function, and how rarely this will be called :)

2023-02-16 16:22 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +_groupPositionASL = AGLToASL _groupPositionAGL;
Think this wants a `private` before it :)

2023-02-16 16:22 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +        private _totalNearbyEnemies = { side _x in _enemySides } count (_safePosition nearEntities ["AllVehicles", _enemyAvoidanceDistance]);
`CAManBase` would be better than `AllVehicles` here, as that returns only Units ,:)

2023-02-16 16:22 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +        private _totalNearbyFriendlies = { !(side _x in _enemySides) } count (_safePosition nearEntities ["AllVehicles", _minDistanceFromTeam]);
Same again about `CAManBase`

2023-02-16 16:22 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +private _safeSpawnTransform = call vgm_s_fnc_respawn_getInitialSpawnPointMarkerTransform; // fallback spawn position if a safe one can't be found near teammates
I've rethought this - let's spawn on top of a random teammate if there's no good spawn position. It disrupts the game flow less. If we spawn a player back at base, they've not got a way back to the mission.

Only just thought of this 😅

2023-02-16 16:22 UTC, Spoffy commented on game/mission/description.ext
> +    "76561198008065973",
👍

2023-02-16 16:22 UTC, Spoffy commented on game/mission/respawn.hpp
> +respawnTemplates[] = { "vgm_respawn" };
Overwriting the respawn system entirely like this feels elegant to me 👍

2023-02-17 16:41 UTC, gnalvesteffer commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    private _nearGroupMembers = (_unit nearEntities ["AllVehicles", LONEWOLF_DISTANCE]) select { group _x == _group && _x call _groupMemberPredicate};
Oh that's awesome, I didn't know about `inAreaArray`!

2023-02-17 17:05 UTC, gnalvesteffer commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    };
That sounds right. Also tracking this with just those two variables would be more memory efficient as well.

2023-02-17 17:23 UTC, gnalvesteffer commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    _positionSum = _positionSum vectorAdd [_unitPosition#0, _unitPosition#1, 0];
Actually I just realized that the zero is redundant. Will remove.

2023-02-17 17:25 UTC, gnalvesteffer commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    _unitCountSum = _unitCountSum + 1;
Yup, and it's even simpler now with your other proposed change of tracking the largest group with two variables, one of which is to keep track of the largest group size.

2023-02-17 17:27 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +        private _totalNearbyEnemies = { side _x in _enemySides } count (_safePosition nearEntities ["AllVehicles", _enemyAvoidanceDistance]);
Probably just an ARMA-ism, but is there a reason to use `CAManBase` over just `Man`? I've seen and done this in the past a long time ago but forgot why.

2023-02-17 17:29 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +        private _totalNearbyEnemies = { side _x in _enemySides } count (_safePosition nearEntities ["AllVehicles", _enemyAvoidanceDistance]);
Also I'm checking AllVehicles so that the player isn't spawned near an enemy vehicle. `nearEntities` doesn't check for units in vehicles. Let me know if I should keep this as-is or move forward with only checking for CAManBase, or if you have an alternative solution.

![image](https://user-images.githubusercontent.com/25854043/219724034-92c4d5c0-39ba-4b5d-9e2b-0c1fb5fc1c54.png)

2023-02-17 17:33 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +        private _totalNearbyFriendlies = { !(side _x in _enemySides) } count (_safePosition nearEntities ["AllVehicles", _minDistanceFromTeam]);
With regards to your other comment about using `CAManBase` for enemies, I think it's fine to replace the friendly unit check however, since it might be kinda silly to try to spawn a player near a friendly vehicle that could be driving off, leaving the player stranded, and also putting a bit of a mental toll on other players with having to (sub)consciously stop their vehicle or search for their teammate when they die. It may be disruptive to the overall team.

2023-02-17 17:35 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +private _safeSpawnTransform = call vgm_s_fnc_respawn_getInitialSpawnPointMarkerTransform; // fallback spawn position if a safe one can't be found near teammates
Agreed.

2023-02-17 17:36 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +private _safeSpawnTransform = call vgm_s_fnc_respawn_getInitialSpawnPointMarkerTransform; // fallback spawn position if a safe one can't be found near teammates
Also what should we do if the player is the only one left in their group, either because everyone else died and is in the middle of respawning, or because they're the only one on the server? Should they just respawn somewhere around their place of death? Not opposed to that, since it would be respectful of their time to keep them near the action and not have to trek across country from base. At least as a placeholder for now until more of the mission is fleshed out and another approach makes more sense.

2023-02-18 19:36 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +    private _nearGroupMembers = (_unit nearEntities ["AllVehicles", LONEWOLF_DISTANCE]) select { group _x == _group && _x call _groupMemberPredicate};
InareaArray is one of those absolute A-tier commands for anything area based. I think nearly every algorithm I've put in-game for area stuff uses it now 😆

2023-02-18 19:44 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +        private _totalNearbyEnemies = { side _x in _enemySides } count (_safePosition nearEntities ["AllVehicles", _enemyAvoidanceDistance]);
Ah, good thinking on the enemy vehicles, that didn't occur to me. I think leave it for now then :)

2023-02-18 20:03 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +        private _totalNearbyFriendlies = { !(side _x in _enemySides) } count (_safePosition nearEntities ["AllVehicles", _minDistanceFromTeam]);
The vehicle edge case is an interesting one. I'm not strongly feeling one way or another on this. I'm not particularly fussed about including vehicles in this check or not - I can thinks of reasons for both behaviours.

Based on that, I wonder if we should just make this into `units group _unitToRespawn inAreaArray []` too, as it'll make the check a little more performance friendly, and include vehicles?

2023-02-18 20:05 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +private _safeSpawnTransform = call vgm_s_fnc_respawn_getInitialSpawnPointMarkerTransform; // fallback spawn position if a safe one can't be found near teammates
Yay, edge cases! 😆. If everyone has died, it's game over, at least under the current designs. But to cover our edge cases... yeah, somewhere around their place of death makes a lot of sense, as it behaves sensibly in all situations, even if that particulary scenario is hit through a bug, or the mission fails to end (for example).

2023-02-18 20:11 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +_groupPositionASL = AGLToASL _groupPositionAGL;
Oops, good catch!

2023-02-18 20:36 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findSafeSpawnTransformNearTeam.sqf
> +    private _safePosition = [_groupPositionASL, _minDistanceFromTeam, _maxDistanceFromTeam, 5, 0, 30, 0, [], [[0, 0], [0, 0]]] call BIS_fnc_findSafePos;
Agreed

2023-02-18 20:39 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_getInitialSpawnPointMarkerTransform.sqf
> +    [getPosASL player, direction player]; // TODO: remove before merge -- this is only for testing!!!
Added a hint, error log, and systemChat:
![image](https://user-images.githubusercontent.com/25854043/219897502-b1a952b7-eed3-4027-83d0-2969f2a47473.png)

2023-02-21 01:02 UTC, Spoffy reviewed
Couple of minor bits, but looking great 👍

2023-02-21 01:02 UTC, Spoffy commented on game/functions/systems/respawn/server/fn_respawn_findFallbackSpawnTransform.sqf
> +private _fallbackSpawnPositionASL = AGLToASL (([_fallbackSpawnUnitPositionASL, _minDistanceFromTeam, _maxDistanceFromTeam, 5, 0, 30, 0, [], [[0, 0], [0, 0]]] call BIS_fnc_findSafePos) vectorAdd [0, 0
What does the vectorAdd at the end of this line do? :)

2023-02-21 01:02 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +        _groupMemberPredicate - The condition that must be satisfied to count as a nearby group member. [CODE]. Optional.
It'd be more with our usual convention I think to pass the predicate in this form:
```sqf
[
    [_arg1, _arg2],
    {
        // Predicate code
    }
]
```
As that's the format we typically use for callbacks and event handlers, etc.

2023-02-21 01:02 UTC, Spoffy commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +        _groupMemberPredicate - The condition that must be satisfied to count as a nearby group member. [CODE]. Optional.
Usually we then do something like this:
```sqf
if (_predicate isEqualType {}) then {
    _predicate = [[], _predicate]
};
```
To standardise the format, and allow only a code block to be passed :)

2023-02-21 01:04 UTC, gnalvesteffer commented on game/functions/systems/respawn/server/fn_respawn_findFallbackSpawnTransform.sqf
> +private _fallbackSpawnPositionASL = AGLToASL (([_fallbackSpawnUnitPositionASL, _minDistanceFromTeam, _maxDistanceFromTeam, 5, 0, 30, 0, [], [[0, 0], [0, 0]]] call BIS_fnc_findSafePos) vectorAdd [0, 0
BIS_fnc_findSafePos returns a 2D AGL position, so my vector add is just a trick to turn it into a 3D position with the altitude being 0, so I can convert it to ASL.

2023-02-21 01:09 UTC, gnalvesteffer commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +        _groupMemberPredicate - The condition that must be satisfied to count as a nearby group member. [CODE]. Optional.
Oh yea that's a lot better since it groups the predicate with its args when calling the function, will change this.

2023-02-22 05:15 UTC, gnalvesteffer commented on paradigm/global/functions/helpers/fn_get_group_majority_position.sqf
> +        _groupMemberPredicate - The condition that must be satisfied to count as a nearby group member. [CODE]. Optional.
Might be something we can extract to a function later on if we ever get to a point where we're frequently performing this predicate type sanitization.

2023-02-22 05:49 UTC, gnalvesteffer commented
@Spoffy Ready for review

2023-02-23 21:08 UTC, Spoffy approved these changes

2023-02-23 23:58 UTC, merged