Sites hints - Add system
Savage-Game-Design/Across-the-Fence pull request #173
Opened 2024-10-30 21:43 UTC by veteran29

Depends on #161

2024-11-15 01:44 UTC, Spoffy requested changes
Really happy with this, just pointed out a few small bits :)

2024-11-15 01:44 UTC, Spoffy commented on game/functions/systems/sites_hints/client/fn_sites_hints_glintJob.sqf
> +private _radius = linearConversion [0, 1, vgm_c_skill_investigate_intensity, RADIUS_MAX, RADIUS_MIN];
```suggestion
#define RADIUS 200
#define OBJECTS_MAX 50

private _interval = linearConversion [0, 1, vgm_c_skill_investigate_intensity, GLINT_JOB_INT_MAX, GLINT_JOB_INT_MIN];
private _radius = RADIUS;
```

2024-11-15 01:44 UTC, Spoffy commented on game/functions/systems/sites_hints/client/fn_sites_hints_glint.sqf
> +addMissionEventHandler ["Draw3d", {
All Draw3D handlers fire when alt-tabbing back into the game, making the glints effectively "queue" and all show at once

2024-11-15 01:44 UTC, Spoffy commented on game/functions/systems/sites_hints/client/fn_sites_hints_initObject.sqf
> +        [parameter] call vgm_c_fnc_sites_hints_initObject
```suggestion
    Returns:
        Nothing

    Example(s):
        [allSitesObjects # 0, [[0, 0, 0]]] call vgm_c_fnc_sites_hints_initObject
```

2024-11-15 01:44 UTC, Spoffy commented on game/functions/systems/sites_hints/client/fn_sites_hints_preInit.sqf
> +];
👍 , I like this

2024-11-15 01:44 UTC, Spoffy commented on game/functions/systems/sites_hints/server/fn_sites_hints_place.sqf
> +        Something [BOOL]
```suggestion
        Nothing
```

2024-11-15 02:38 UTC, veteran29 commented on game/functions/systems/sites_hints/client/fn_sites_hints_glint.sqf
> +addMissionEventHandler ["Draw3d", {
Fixed by switching to EachFrame EH

2024-11-16 15:21 UTC, Spoffy approved these changes

2024-11-20 17:40 UTC, merged