Missions - Hide blue target box overlay
Savage-Game-Design/Across-the-Fence pull request #176
Opened 2024-11-02 03:09 UTC by Spoffy

Also removes some old tracker code.

2024-11-11 15:58 UTC, veteran29 requested changes

2024-11-11 15:58 UTC, veteran29 commented on game/functions/systems/locations/global/fn_loc_getTargetBoxMarker.sqf
> +format ["tbox_%1", _targetBox]
There's already `vgm_g_fnc_missions_getZoneMarker`, maybe one should call the other?

2024-11-11 15:58 UTC, veteran29 commented on game/functions/systems/locations/global/fn_loc_getTargetBoxMarker.sqf
> +        ["oscar8"] call vgm_g_fnc_loc_getTargetBoxBounds;
```suggestion
        ["oscar8"] call vgm_g_fnc_loc_getTargetBoxMarker;
```

2024-11-11 15:58 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_coverMap.sqf
> +[_zone] call vgm_g_fnc_loc_getTargetBoxMarker setMarkerAlphaLocal 0;
Not sure if we even need the function, there's already one for this.
```suggestion
_zone call vgm_g_fnc_missions_getZoneMarker setMarkerAlphaLocal 0;
```

2024-11-15 01:58 UTC, Spoffy commented on game/functions/systems/missions/client/fn_missions_coverMap.sqf
> +[_zone] call vgm_g_fnc_loc_getTargetBoxMarker setMarkerAlphaLocal 0;
There wasn't in this branch when I was making it! 😆

2024-11-15 02:01 UTC, Spoffy commented on game/functions/systems/locations/global/fn_loc_getTargetBoxMarker.sqf
> +format ["tbox_%1", _targetBox]
Didn't exist when this was made - updated missions_getZoneMarker to use it :)

2024-11-15 02:41 UTC, veteran29 approved these changes

2024-11-16 15:18 UTC, merged