Skills - Draws players on the artillery map if skill is owned
Savage-Game-Design/Across-the-Fence pull request #178
Opened 2024-11-07 00:03 UTC by Spoffy

2024-11-07 13:51 UTC, veteran29 requested changes

2024-11-07 13:51 UTC, veteran29 commented on game/functions/systems/squad_ui/client/fn_squad_ui_enablePlayersOnArtilleryMap.sqf
> +}];
Would be better to have a wrapper function for opening the artillery display, the function should wait for the display to open and then add the Draw EH.

2024-11-09 21:35 UTC, Spoffy commented on game/functions/systems/squad_ui/client/fn_squad_ui_enablePlayersOnArtilleryMap.sqf
> +}];
Done - rewrote how this is done.

Now we initialise the artillery system internally, wrap the call to open the display, and emit an event with it opens that squad_ui can hook into.

2024-11-09 21:35 UTC, Spoffy commented on game/functions/systems/squad_ui/client/fn_squad_ui_enablePlayersOnArtilleryMap.sqf
> +}];
Good suggestion - it took a bit of time to do, but this is much cleaner, and opens the door to us emitting other artillery-related events if needed.

2024-11-09 21:56 UTC, Spoffy commented on game/functions/systems/squad_ui/client/fn_squad_ui_enablePlayersOnArtilleryMap.sqf
> +}];
Oh, I also add/remove radio support actions at the start/end of the mission, so players can't call it in the base.

2024-11-11 15:46 UTC, veteran29 approved these changes

2024-11-11 15:46 UTC, veteran29 commented on game/functions/systems/artillery/client/fn_artillery_menu.sqf
> +        sleep 0.1;
No point in short sleep and for such cheap code. Wait until checks at most once a frame.
```suggestion
```

2024-11-11 15:46 UTC, veteran29 commented on game/functions/systems/artillery/global/fn_artillery_postInit.sqf
> +    }] call para_g_fnc_event_subscribeLocal;
Would be good to prevent unconscious player from calling support. Would need hooking into `vgm_medical_unconscious`

2024-11-11 21:10 UTC, merged