Skills - Swap tiers of Keen Eye and Better Aim
Savage-Game-Design/Across-the-Fence pull request #182
Opened 2024-11-13 19:22 UTC by veteran29

- title
- Also add "Better Aim" name to the skill and move current name to description

2024-11-13 23:30 UTC, Spoffy requested changes

2024-11-13 23:30 UTC, Spoffy commented on game/configs/mission/cfg_skills.hpp
> +                    description = "STR_VGM_SKILLS_SKILL_RECON_BETTER_AIM_DESC";
No $ at the start of this description, but there is for the `keenEye` description. Not sure what's correct, just flagging the discrepency.

2024-11-14 17:05 UTC, veteran29 commented on game/configs/mission/cfg_skills.hpp
> +                    description = "STR_VGM_SKILLS_SKILL_RECON_BETTER_AIM_DESC";
Fixed translation

2024-11-15 00:07 UTC, Spoffy approved these changes

2024-11-15 02:39 UTC, merged