Tutorial - Add basic framework
Savage-Game-Design/Across-the-Fence pull request #184
Opened 2024-11-17 16:50 UTC by Spoffy

Adds support for CfgHints entries to show as a survival card hint, when triggered by one of these conditions:
- Entering a specific marker on the map
- The client receiving a specific event from any source
- Looking at an object with `vgm_c_tutorial` set to the path of the tutorial.

2024-11-20 18:14 UTC, veteran29 requested changes

2024-11-20 18:14 UTC, veteran29 commented on game/functions/systems/tutorial/client/fn_tutorial_postInit.sqf
> +                "this && player in thisList",
Lazy eval would be slower here most likely so we can simply omit `this`.
```suggestion
                "player in thisList",
```

2024-11-20 18:14 UTC, veteran29 commented on game/functions/systems/tutorial/client/fn_tutorial_preInit.sqf
> +
```suggestion

if (!hasInterface) exitWith {};
```

2024-11-20 18:14 UTC, veteran29 commented on game/functions/systems/tutorial/client/fn_tutorial_preInit.sqf
> +["TutorialAcknowledgeHint", para_c_fnc_ui_hints_acknowledgeHintKeypress] call para_c_fnc_keyhandler_addGeneralActionHandler;
I feel like we should re-use vanilla `help` action for this.
<https://community.bistudio.com/wiki/addUserActionEventHandler>
<https://community.bistudio.com/wiki/inputAction/actions>
`help` is the action name for vanilla Adv Hints.

2024-11-20 18:14 UTC, veteran29 commented on game/functions/systems/tutorial/client/fn_tutorial_trigger.sqf
> +if (_key in vgm_c_tutorial_seenTutorials) exitWith {};
This is good enough for now but I feel like we could filter out seen tutorials during mission init and not even create a hooks for them.

2024-11-20 21:13 UTC, Spoffy commented on game/functions/systems/tutorial/client/fn_tutorial_trigger.sqf
> +if (_key in vgm_c_tutorial_seenTutorials) exitWith {};
Agreed

2024-11-20 21:14 UTC, Spoffy commented on game/functions/systems/tutorial/client/fn_tutorial_preInit.sqf
> +["TutorialAcknowledgeHint", para_c_fnc_ui_hints_acknowledgeHintKeypress] call para_c_fnc_keyhandler_addGeneralActionHandler;
That seems reasonable. Do these handle being in UIs, menus, correctly?

2024-11-21 18:17 UTC, veteran29 commented on game/functions/systems/tutorial/client/fn_tutorial_preInit.sqf
> +["TutorialAcknowledgeHint", para_c_fnc_ui_hints_acknowledgeHintKeypress] call para_c_fnc_keyhandler_addGeneralActionHandler;
It seems to work only in main display and not on dialogs. Could use `actionKeysEx` to get the default value of the bind but I realized it's `H` by default which would collide with medical menu, so disregard this comment.

2024-11-21 18:35 UTC, veteran29 approved these changes

2024-11-21 21:36 UTC, merged