Adds mission framework and netmap utility
Savage-Game-Design/Across-the-Fence pull request #19
Opened 2023-02-26 22:17 UTC by Spoffy

2023-06-23 16:31 UTC, veteran29 requested changes

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_getCurrentMission.sqf
> +_missions get (_assignments get (getPlayerID player))
If this is expected to return `nil` then the `getOrDefault` is not needed.

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_makeMissionGiver.sqf
> +    "isNil vgm_c_fnc_missions_getCurrentMission",
Pretty sure this should check if the function result is nil, not if the function itself is `nil`.
```suggestion
    "isNil {call vgm_c_fnc_missions_getCurrentMission}",
```

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_makeMissionGiver.sqf
> +localNamespace setVariable ["vgm_c_fnc_addJoinMissionAction", {
Why not missionNamespace for easier access?

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_makeMissionGiver.sqf
> +        "!(isNil vgm_c_fnc_missions_getCurrentMission)",
```suggestion
        "!isNil {call vgm_c_fnc_missions_getCurrentMission}",
```

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_postInit.sqf
> +
```suggestion

if (!hasInterface) exitWith {};

```

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_preInit.sqf
> + */
```suggestion
 */
 
 if (!hasInterface) exitWith {};
```

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/internal/fn_missions_finishDeploy.sqf
> +        []  remoteExecCall ["vgm_c_fnc_missions_finishDeploy", _player];
```suggestion
        [] remoteExecCall ["vgm_c_fnc_missions_finishDeploy", _player];
```

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/client/internal/fn_missions_startDeploy.sqf
> +        []  remoteExecCall ["vgm_c_fnc_missions_startDeploy", _player];
```suggestion
        [] remoteExecCall ["vgm_c_fnc_missions_startDeploy", _player];
```

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/server/fn_missions_createMission.sqf
> +params ["_parameters", ["_creatorId", ""]];
Might be reasonable to check types here as the system could break in weird ways if passed for eg. array instead of hashmap.
```suggestion
params [
    ["_parameters", nil, [createHashMap]],
    ["_creatorId", "", [""]]
];
```

2023-06-23 16:31 UTC, veteran29 commented on game/functions/systems/missions/server/fn_missions_preInit.sqf
> +
```suggestion

if (!isServer) exitWith {};

```

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_add.sqf
> + */
Docs

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_deleteAt.sqf
> + */
Docs

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_deleteAt.sqf
> +    format ["Attempted to delete key %1 on non-existent netmap %2", _key, _netmapId] call vgm_g_fnc_logError;
Pardigm function should not use VGM logging function.

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_fixReferences.sqf
> +    };
Not sure, should this be recursive?

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_onReady.sqf
> + */
Docs

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_preInit.sqf
> + */
Docs

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_set.sqf
> +    format ["Attempted to set key %1 on non-existent netmap %2", _key, _netmapId] call vgm_g_fnc_logError;
Paradigm function should not use VGM logging function.

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_set.sqf
> + */
Docs

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_terminate.sqf
> + */
Docs

2023-06-23 16:31 UTC, veteran29 commented on paradigm/client/functions/netmap/fn_netmap_terminate.sqf
> +    format ["Attempted to delete non-existent netmap %1", _netmapId] call vgm_g_fnc_logError;
Paradigm function should not use VGM logging function.

2023-06-23 16:31 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", 0];
What's the reason for this change? I  would rather leave it as is. Remote exec does not happen "in place" like call does and it can be delayed a few frames.
```suggestion
[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", -clientOwner];

_this call para_g_fnc_event_triggerLocal;
```

2023-06-23 16:31 UTC, veteran29 commented on paradigm/global/functions/events/internal/fn_event_attachHandler.sqf
> +[] call para_g_fnc_event_system_init;
With this the event system init can be removed from VGM core.

2023-06-23 16:31 UTC, veteran29 commented on paradigm/server/functions/netmap/fn_netmap_createNamedNetmapFromArray.sqf
> +        p, and makes it available on the client using the given name.
Cut out sentence.

2023-06-23 16:31 UTC, veteran29 commented on paradigm/server/functions/netmap/fn_netmap_createNetmap.sqf
> +params [];
Docs seem wrong, random `params`

2023-06-23 16:31 UTC, veteran29 commented on paradigm/server/functions/netmap/fn_netmap_createNetmapFromArray.sqf
> + */
Docs seem wrong

2023-06-23 16:31 UTC, veteran29 commented on paradigm/server/functions/netmap/fn_netmap_deleteAt.sqf
> +    format ["netmap_deleteAt used on non-netmap hashmap: %1", keys _hashMap] call vgm_g_fnc_logWarning;
VGM logging func in Paradigm code

2023-06-23 16:31 UTC, veteran29 commented on paradigm/server/functions/netmap/fn_netmap_requestAllNetmaps.sqf
> +    format ["machine %1 claimed to be %2 when requesting netmaps", remoteExecutedOwner, _sender] call vgm_g_fnc_logError;
VGM logging func in Paradigm code

2023-06-23 16:31 UTC, veteran29 commented on paradigm/server/functions/netmap/fn_netmap_set.sqf
> +    format ["netmap_set used on non-netmap hashmap: %1", keys _hashMap] call vgm_g_fnc_logWarning;
VGM logging func in Paradigm code

2023-06-23 16:31 UTC, veteran29 commented on paradigm/server/functions/netmap/fn_netmap_terminate.sqf
> +    format ["netmap_terminate used on non-netmap hashmap: %1", keys _hashMap] call vgm_g_fnc_logWarning;
VGM logging func in Paradigm code

2023-06-23 16:45 UTC, veteran29 commented on game/functions/systems/missions/server/fn_missions_createMission.sqf
> +    ["machineIds", createHashMap]
I feel like the direct play to machine ID mapping could be stored in a global hashmap in `core` component instead of having it in the mission hashmaps.

2023-06-23 22:36 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_createMission.sqf
> +    ["machineIds", createHashMap]
Couuuld do, I was avoiding something like:

```sqf
private _playerIds = ([_mission get "players"] call para_g_fnc_netmap_keys);
private _machineIds = _playerIds apply {_x call vgm_s_fnc_playerIdtoMachineId);
```
Everytime we want to send something to just people on that mission, which feels like a bit of a hassle. 

The alternative is we could do both? I could create `vgm_s_fnc_playerIdToMachineId`, then use that to fill the hashmap in the mission?

2023-06-23 22:39 UTC, Spoffy commented on paradigm/client/functions/netmap/fn_netmap_fixReferences.sqf
> +    };
Doesn't need to be thankfully. If the netmap exists in the netmaps lookup table, it's already had all its references resolved. 

The only exception is when the `netmaps` are initially populated on join, but we call it on every single one then anyway, so we're golden 👍

2023-06-23 22:42 UTC, Spoffy commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", 0];
Originally, I had code like this:
```sqf
[] remoteExecCall ["update_something", 0];

["mything", []] call para_g_fnc_event_triggerGlobal;
```

Which meant there was a subtle ordering problem, where the event fired before the data had been updated.

Since moving to netmaps, I think it's solved this problem as there's no delayed execution when you call `para_s_fnc_netmap_set`. I'll need to double check though.

2023-06-23 22:42 UTC, Spoffy commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", 0];
If it has, I'll walk this change back, since I see you need it in your other PR to behave like this.

2023-06-24 01:53 UTC, Spoffy commented on game/functions/systems/missions/client/fn_missions_makeMissionGiver.sqf
> +localNamespace setVariable ["vgm_c_fnc_addJoinMissionAction", {
True, doesn't really matter since this is a debug command.

2023-06-24 01:54 UTC, Spoffy commented on game/functions/systems/missions/client/fn_missions_makeMissionGiver.sqf
> +    "isNil vgm_c_fnc_missions_getCurrentMission",
Technically it works, since the function variable is a code block, it gets executed :D.

But I agree this is really unclear, so I'll do it the way you suggested :)

2023-06-24 01:55 UTC, Spoffy commented on game/functions/systems/missions/client/fn_missions_getCurrentMission.sqf
> +_missions get (_assignments get (getPlayerID player))
Did not realise `get` handles nil variables properly. I'll update this.

2023-06-24 23:49 UTC, veteran29 commented on game/functions/systems/missions/server/fn_missions_createMission.sqf
> +    ["machineIds", createHashMap]
Looking at it again, I think there's no need, the function would basically do `getUserInfo _playerId select 1`

2023-06-24 23:59 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_getCurrentMission.sqf
> +_missions get (_assignments get (getPlayerID player))
It's not a matter of `get` handling `nil` properly. Any command when given a `nil` returns a `nil`. If execution is unscheduled then it's silent, in case of scheduled code if `_variable` is nil then error is logged, if nil is given explicitly it will be silent in both cases.

see: https://foxhound.international/arma-3-sqf-nil.html

2023-06-25 00:02 UTC, veteran29 commented on game/functions/systems/missions/client/fn_missions_getCurrentMission.sqf
> +_missions get (_assignments get (getPlayerID player))
The defaults should be left in place if you expect to execute this in `scheduled` env.

2023-06-25 14:37 UTC, Spoffy commented on game/functions/systems/missions/client/fn_missions_getCurrentMission.sqf
> +_missions get (_assignments get (getPlayerID player))
Ah, didn't realise the scheduled environment is what causes `nil` variables to error. Yes, there's every chance this will be run scheduled, so will leave it as is.

2023-06-25 16:54 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", 0];
Looking at it again, the original problem could also be avoided if you would use event for both things instead of RE. In general it's a good idea to not mix them in one component. Choose one or another.

2023-06-30 13:27 UTC, Spoffy commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", 0];
The netmap changes resolved it. :)

2023-07-01 11:45 UTC, veteran29 approved these changes

2023-07-01 11:45 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf.bak
> +[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", 0];
Should this file be there?

2023-07-02 23:44 UTC, Spoffy commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf.bak
> +[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", 0];
Nope, I'll remove it, must have accidentally added it.

2023-07-03 00:05 UTC, Spoffy commented
Removed that old .bak file.

Merged in 582f2c2d889ecbc8d707e6b86050601935de9edf manually, with rebasing + squashing to keep the history clean.

2023-07-03 00:05 UTC, closed without merging