Persistence API #2x1z4ae
Savage-Game-Design/Across-the-Fence pull request #2
Opened 2022-11-03 22:06 UTC by cerebral-314

2022-11-03 22:06 UTC, SavageGameDesign commented
Task linked: [CU-2x1z4ae Persistence API basics that supports multiple backends, backed by profile](https://app.clickup.com/t/2x1z4ae)

2022-11-05 18:52 UTC, veteran29 requested changes
I'm doing another pass on this Pull Request and I'm not happy with it. I think you made the implementation too specific and focused on the player persistence instead of generic persistence feature.

### General design considerations:

Going over features described in the task:

**1.**
> Basic key-value store functionality (save key with data, load data from key)

There's no wrapper functions for this functionality at all, instead we have direct usage of `profileNamespace` or SQL queries via extDB3. Thinking about how the gamemodes in arma usually work I _feel_ like we should generic functions with signatures like:
```sqf
[<table>, <id>] call vgm_fnc_db_get;
[<table>, <id>, <data>] call vgm_fnc_db_set;

[] call vgm_fnc_db_commit; // saves missionProfileNamespace, in case of remote DB might do nothing depending if we want to use transactions or not
[] call vgm_fnc_db_clear; // most likely only available for missionProfileNamespace
```

**2.**
> Single API, multiple backends - we should be able to use profiledb initially, and easily swap to a shared database later

It's somewhat(ish) here but does not feel like it's abstracted enough (due to above point), SQL queries plainly in the functions that use the DB. 

Personally, I feel like we should not implement external database right now. The current extDB3 implementation feels like a technical debt to me already. Storing text (sqf array) data in single column is pretty meh and would be bit annoying to use in let's say external database with player stats etc.

If and when we will want external storage we IMHO should have custom solution, which could be quickly built with something like `arma-rs` which could allow us to use proper models on extension side if we want, has neat features for converting Rust structs to Arma data and opposite and is quite fast to develop in.

**3.**
> Initial implementation using profile or mission profile.

We should use missionProfileNamespace as this is better for people local hosting, bloating player profile is bad as it can cause stutters. There's no reason to use `profileNamespace` over `missionProfileNamespace`.

**4.**
> Supports clearing all data for easy testing / mission resets

We lack generic implementation so does not apply r/n.

**5.**
> Accepts hashmaps, arrays, strings, numbers as a minimum

We lack generic implementation so does not apply r/n.

#### Example:

Let's say we have a custom _playerSkills_ component, to get known skills on the player load we would have function like:
```sqf
vgm_fnc_playerSkills_get = {
    params ["_playerUID"];

    ["player_skills", _playerUID] call vgm_fnc_db_get // return
};
```

For `missionProfileNamespace` the implementation of `db_get` could be simply:
```sqf
vgm_fnc_db_get = {
    params ["_key", "_id", "_data"];

    missionProfileNamespace getVariable [format ["vgm_%1_%2", _key, _id]] // return
};
```

For the database, be it either some document store like Mongo or relational DB like Postgres it will `callExtension`. Simple and should work fine for 99% of use cases.

### General code style comments:

The braces are not consistent, some parts have brace in same line as `then` some on next line. We should prefer same line for more compact code.

Wayyy too many comments over every single thing, it goes to the point where it darkens the code.
Simple and obvious things do not need comments, if something is not clear we should try using descriptive variable names instead, if possible ofc.

Example of the comments which are not that useful:

// we can see it's an empty array
```sqf
// create empty array for playerVars
_vars = [];
```

// quite obvious, what the comment states is litteraly part of the command name
```sqf
// Get player's UID
private _playerUID = getPlayerUID player;
```

// good idea with the variable name, it's descriptive, so no need for a comment that conveys the same thing
```sqf
// Create a new HashMap to return with
private _returnHashMap = createHashMap;
```

// this is simply false comment, it's last line of the file, thus it's a return.
```sqf
// Add all player variables to the return HashMap
_profile;
```
etc.


As SQF has no explicit return statement I find it good practice to mark them with `// return` comments, like this:
```sqf
fnc_returnExample = {
    if (_something) exitWith {
        123 // return
    };

    312 // return
};
```

2022-11-11 21:49 UTC, Spoffy requested changes

2022-11-11 21:49 UTC, Spoffy commented on game/functions/core/server/db/fn_db_get.sqf
> +_result // return
I've been thinking about this, and I'm wondering if we should have two commands: a raw DB set/get command, and ones that do key and id.

My thinking is we might want a lower level of DB access in the future, but still without having to deal with the missionProfileNamespace directly.

So maybe something like:
```
[_key, _value] call vgm_fnc_db_save;
["player", _key, _value] call vgm_fnc_db_save_type;
```
Or similar? What do you think?

2022-11-11 21:49 UTC, Spoffy commented on game/functions/core/server/db/fn_db_get.sqf
> +_result // return
(Also - my naming there is... a bit meh, so if you've better ideas I'm all ears!)

2022-11-11 21:49 UTC, Spoffy commented on game/functions/core/server/db/fn_db_set.sqf
> +	diag_log format ["VGM: Failure to save %1(%2). Data is not a hashmap: %2", _key, _id, _data];
For logging in general, can we use https://github.com/Savage-Game-Design/Paradigm/blob/development/global/functions/logging/fn_log.sqf instead of diag_log? As it'll give us tool integration later :)

I like the check here, but I'm wondering if we need to restrict it to just hashmaps? Profile namespace supports arbitrary variable types, so it feels like we should be safe allowing the user to store whatever they want.

2022-11-11 21:49 UTC, Spoffy commented on game/functions/core/server/db/fn_db_set.sqf
> +};
I like what you've gone for here. I'm wondering if we want to do versioning per-entity, or whether it would be better to do versioning on the whole save, and just upgrade the whole save when we push a new version out. It feels like that might be simpler to track and manage going forwards?

Would like your thoughts on it though, as I'm definitely not sure.

2022-11-11 21:59 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_get.sqf
> +_result // return
I think it'd be a good idea... I could include the key type inside the value just to ensure you'll be using the proper schema when/if we switch backends.

2022-11-11 22:02 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_set.sqf
> +	diag_log format ["VGM: Failure to save %1(%2). Data is not a hashmap: %2", _key, _id, _data];
Alrighty will swap to fn_log.

I'd like it to remain only hash maps because hash maps can hold arbitrary variable types as well. It just seems proper for a key/value database structure.
With the current configuration it'd be very easy to translate this to any database type. It outputs as a array which is very JS friendly(assuming we head in the MongoDB direction with the extension... assuming we do that as well haha).

2022-11-11 22:05 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_set.sqf
> +};
Yeah definitely... my thought process was what if we wanna "upgrade" the player structure via SQL. Would be a real quick query to separate the old from the new.

2022-11-11 22:08 UTC, Spoffy commented on game/functions/core/server/db/fn_db_get.sqf
> +_result // return
+1. I like the idea of including the key type in the hashmap too.

2022-11-11 22:10 UTC, Spoffy commented on game/functions/core/server/db/fn_db_set.sqf
> +	diag_log format ["VGM: Failure to save %1(%2). Data is not a hashmap: %2", _key, _id, _data];
Cool - that's fair, I don't really have a strong argument for not using hashmaps. I *suspect* we'll end up writing wrappers like: `vgm_fnc_db_save_player` and `vgm_fnc_db_save_all_vehicles`, etc, anyway, so the hashmap vs arbitrary value debate wouldn't make a difference to the usual usage anyway.

2022-11-11 22:17 UTC, Spoffy commented on game/functions/core/server/db/fn_db_set.sqf
> +};
Yeah, the more I think about it, the more saving a version per entity makes sense, if we end up with multiple servers sharing one database. 

I think versioning the whole DB would cause us issues with having to shut down all the servers and upgrade the whole DB of content before being able to upgrade the servers.

Can I propose though that when we split the `db_set` functions into `db_save` and `db_save_type` variants, we only include the `version` tag insertion in the `db_save_type` function? :)

2022-11-11 22:18 UTC, Spoffy commented on game/functions/core/server/db/fn_db_set.sqf
> +	diag_log format ["VGM: Failure to save %1(%2). Data is not a hashmap: %2", _key, _id, _data];
(To be clear - that's a 👍 for hashmaps)

2022-11-11 22:56 UTC, Spoffy commented on game/functions/core/server/db/fn_db_get.sqf
> +_result // return
We can remove the return comment I think, the lack of semicolon is what we usually use to distinguish that :)

2022-11-11 22:57 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_get.sqf
> +_result // return
Filip told me to do this but I will :P

2022-11-11 23:02 UTC, Spoffy commented on game/functions/core/server/db/fn_db_save.sqf
> +if (_data find "key" == -1) exitWith {
I'm thinkg this function shouldn't check key - I think the idea for this function is that `_id` is the full key.
E.g, on line 39, we should have:
`format ["vgm_%1", _id]`.

Then db_save_type calls:
```
[format ["%1_%2", _type, _id], _value] call vgm_fnc_db_save
```

If that makes sense? As right now, I think both functions are more or less doing the same thing. My thinking is that this then gives you the option of going "Nah, forget types, this should just be written to the DB as-is". For example, we might want to do:
```
["version", createHashMapFromArray [["number", "3.2"]]] call vgm_fnc_db_save
```
And also
```
["player", getPlayerUID _player, createHashMap] call vgm_fnc_db_save_type
```

2022-11-11 23:03 UTC, Spoffy commented on game/functions/core/server/db/fn_db_save.sqf
> +if (_data find "key" == -1) exitWith {
Hopefully the examples get across the difference in utility between the two? :)

2022-11-11 23:04 UTC, Spoffy commented on game/functions/core/server/db/fn_db_save_type.sqf
> +if !(_data find "key" == -1) then {
We can use `"key" in _data` to check if a key exists in a hashmap :)

2022-11-11 23:04 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_save_type.sqf
> +if !(_data find "key" == -1) then {
I keep forgetting about that one lmao sorry.

2022-11-13 15:07 UTC, veteran29 requested changes
Some minor code formatting suggestions and functionality change ideas.

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_clear.sqf
> +} forEach allVariables missionProfileNamespace;
Missing EOL.

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_clear.sqf
> +    Returns: nothing
If we want to match the style we use in the DLC (and the one added to automatic file headers extension, ref #5 )
```suggestion
    Returns:
        Nothing
```

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_save.sqf
> +    Returns: nothing
```suggestion
    Returns:
        Nothing
```

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_save_type.sqf
> +        ["player", _playerUID, _playerProfile] call vgm_s_fnc_db_save_type;
I'm not the fan of `save_type` name, does not feel intuitive to me, not sure what would be the better name 😅

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_save.sqf
> +missionProfileNamespace setVariable [format ["vgm_%1", _id], _data];
I'm wondering if we shouldn't rename this function to something like `save_raw` and do not do any key formating/prefixing in this one.

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_save_type.sqf
> +};
Should be faster to not use the `if ! in then` (4 commands).
(_insertOnly: Boolean - (Optional, default false) if set to true, set the value only if the key does not exist already_)

```suggestion
private _vgmID = format ["vgm_%1_%2", _key, _id];
// set key and id only if not present in data already
_data set ["key", _key, true];
_data set ["id", _vgmID, true];
```

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_save_type.sqf
> +[_formattedID, _data] call vgm_s_fnc_db_save;
**IF** we would change `save` function to `save_raw` as in my suggestion we would have to use the prefixed ID here.
```suggestion
[_vgmID, _data] call vgm_s_fnc_db_save;
```

2022-11-13 15:07 UTC, veteran29 commented on game/functions/core/server/db/fn_db_get.sqf
> +_result
Why do we need to handle arrays here?

Saving API does not support saving anything else than hashmaps. This does not feel needed. If we have garbage data/arrays in save it's broken most likely anyway.

2022-11-13 15:19 UTC, Spoffy commented on game/functions/core/server/db/fn_db_save_type.sqf
> +        ["player", _playerUID, _playerProfile] call vgm_s_fnc_db_save_type;
Yeah, I said that when I suggested the function name to Cerebral. Really not sure what else to call it, but 'save type' sounds like you're saving a type. 

Maybe `typed_save` would be better?

2022-11-13 15:20 UTC, Spoffy commented on game/functions/core/server/db/fn_db_save.sqf
> +missionProfileNamespace setVariable [format ["vgm_%1", _id], _data];
I'm thinking we leave it for now, and can pull out a `save_raw` later really easily if we find we need it?

2022-11-13 15:20 UTC, Spoffy commented on game/functions/core/server/db/fn_db_save_type.sqf
> +};
Oh, I like this, completely forgot insert only existed as a parameter

2022-11-13 15:26 UTC, veteran29 commented on game/functions/core/server/db/fn_db_save.sqf
> +missionProfileNamespace setVariable [format ["vgm_%1", _id], _data];
I'm not a fan that `save_type` does the same formatting and we do it in two places. I do not insist on name change.

2022-11-13 15:46 UTC, veteran29 commented on game/functions/core/server/db/fn_db_save_type.sqf
> +_data set ["version", getText(missionConfigFile >> "version")];
See #7 
```suggestion
_data set ["version", vgm_version];
```

2022-11-13 16:41 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_get.sqf
> +_result
HashMaps can be saved to the missionProfileNamespace. However theyre not persistent. This was just the beginning of serializing/deserializing to an array so the namespace saves it and it actually persists.

2022-11-13 16:47 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_save_type.sqf
> +};
Ah I like this as well... forgive me I'm a noob when it comes to hashmaps. :P

2022-11-13 16:50 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_save_type.sqf
> +_data set ["version", getText(missionConfigFile >> "version")];
Ah I was wondering where that disappeared to... Thanks for the correction.

2022-11-13 17:15 UTC, veteran29 commented on game/functions/core/server/db/fn_db_get.sqf
> +_result
What do you mean they're not persistent, everything that works in `profileNamespace` works in the mission variant too.

Have you actually saved the namespace (`saveMissionProfileNamespace`)?

2022-11-13 19:31 UTC, cerebral-314 commented on game/functions/core/server/db/fn_db_get.sqf
> +_result
Well after testing again it yields different results... baffling. I was calling saveMissionProfileNamespace as well...

I'll go ahead and make it take hashmaps only.

2022-12-02 17:18 UTC, veteran29 approved these changes
LGTM, we should get this merged so we can continue with other features.

We can always refine it during the development.

2022-12-03 11:03 UTC, merged