Hints - Mark inspected hints on a map
Savage-Game-Design/Across-the-Fence pull request #218
Opened 2024-12-16 18:51 UTC by veteran29

- title
- Also disable glinting for already inspected objects

2024-12-17 02:08 UTC, Spoffy requested changes

2024-12-17 02:08 UTC, Spoffy commented on game/functions/systems/mission_objects/global/fn_mission_objects_call.sqf
> +if (remoteExecutedOwner != 2) then {
Can we use exitWith here to outright prevent this being something other clients can call?

2024-12-17 02:08 UTC, Spoffy commented on game/functions/systems/sites_hints/client/fn_sites_hints_markOnMap.sqf
> +private _marker = createMarkerLocal [format ["vgm_sites_hints_%1", _object], getPosATL _object];
Do we do anything to clean these markers up on mission exit?

2024-12-19 18:21 UTC, veteran29 commented on game/functions/systems/sites_hints/client/fn_sites_hints_markOnMap.sqf
> +private _marker = createMarkerLocal [format ["vgm_sites_hints_%1", _object], getPosATL _object];
It's not cleaned up, derp.

2025-01-03 05:45 UTC, Spoffy approved these changes

2025-01-03 16:35 UTC, merged