Swaps event system to be push-based
Savage-Game-Design/Across-the-Fence pull request #22
Opened 2023-04-14 20:47 UTC by Spoffy

2023-04-21 23:50 UTC, cerebral-314 reviewed
Looks good aside from some comment stuff.
Are we storing the events as a string array or a actual hashmap?

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/fn_event_subscribeToClients.sqf
> +        It's safe to assume that once this function has been called, all
Seems like you've forgotten to complete this.

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +    File: fnc_event_triggerGlobal.sqf
Should be fn_event_triggerGlobal.sqf

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/fn_event_triggerServer.sqf
> +    File: fnc_event_triggerServer.sqf
Should be fn_event_triggerServer.sqf

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/fn_event_triggerServerAndLocal.sqf
> +    File: fnc_event_triggerServerAndLocal.sqf
Should be fn_event_triggerServerAndLocal.sqf

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/fn_event_triggerLocal.sqf
> +    File: fnc_event_triggerLocal.sqf
Should be fn_event_triggerLocal.sqf

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/fn_event_triggerTargets.sqf
> +    File: fnc_event_triggerTargets.sqf
Should be in fn_event_triggerTargets.sqf

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/network/fn_event_remoteExec_trigger.sqf
> +    File: fnc_event_remoteExec_trigger.sqf
Should be fn_event_remoteExec_trigger.sqf

2023-04-21 23:50 UTC, cerebral-314 commented on paradigm/global/functions/events/network/fn_event_remoteExec_trigger.sqf
> +        ["myCustomEvent", 3] call para_g_fnc_event_triggerLocal;
These examples seem to be for para_g_fnc_event_triggerLocal

2023-04-23 16:22 UTC, veteran29 requested changes

2023-04-23 16:22 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +[clientOwner, _event, _data] remoteExec ["para_g_fnc_event_remoteExec_trigger", -clientOwner];
Use `remoteExecCall` for unscheduled execution.
```suggestion
[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", -clientOwner];
```

2023-04-23 16:22 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerGlobal.sqf
> +[clientOwner, _hashableEvent, _event, _data] call para_g_fnc_event_callRegisteredHandlers;
Consider using `triggerLocal` to not duplicate the code.

2023-04-23 16:22 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerServerAndLocal.sqf
> +[clientOwner, _hashableEvent, _event, _data] call para_g_fnc_event_callRegisteredHandlers;
Consider using `triggerLocal` to not duplicate the code.

2023-04-23 16:22 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerTargets.sqf
> +[clientOwner, _event, _data] remoteExec ["para_g_fnc_event_remoteExec_trigger", _targets];
Use `remoteExecCall ` for unscheduled execution.
```suggestion
[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger", _targets];
```

2023-04-23 16:22 UTC, veteran29 commented on paradigm/global/functions/events/fn_event_triggerServerAndLocal.sqf
> +[clientOwner, _event, _data] remoteExec ["para_g_fnc_event_remoteExec_trigger"];
Use `remoteExecCall ` for unscheduled execution.
```suggestion
[clientOwner, _event, _data] remoteExecCall ["para_g_fnc_event_remoteExec_trigger"];
```

2023-04-23 16:22 UTC, veteran29 commented on paradigm/global/functions/events/network/fn_event_remoteExec_trigger.sqf
> +        Remote executed from another clien to trigger the given event.
typo
```suggestion
        Remote executed from another client to trigger the given event.
```

2023-04-23 16:22 UTC, veteran29 commented on paradigm/server/functions/events/internal/fn_event_registerClient.sqf
> +["INFO", format ["Event system - registering client %1", _clientMachineId]] call para_g_fnc_log;
This function does nothing besides logging. Is it intentional?

2023-04-23 18:19 UTC, cerebral-314 commented on paradigm/server/functions/events/internal/fn_event_registerClient.sqf
> +["INFO", format ["Event system - registering client %1", _clientMachineId]] call para_g_fnc_log;
It appears this is modifying the parameter you're giving it to the ID of the client.

2023-04-23 19:29 UTC, veteran29 commented on paradigm/server/functions/events/internal/fn_event_registerClient.sqf
> +["INFO", format ["Event system - registering client %1", _clientMachineId]] call para_g_fnc_log;
It does not as it's using `params` so the variable is "privated" to this scope.

2023-05-07 22:25 UTC, Spoffy commented on paradigm/server/functions/events/internal/fn_event_registerClient.sqf
> +["INFO", format ["Event system - registering client %1", _clientMachineId]] call para_g_fnc_log;
Yeah, it's intentionally left in. It's a handy bit of logging, and gives us something to easily hook into later.

2023-05-12 13:55 UTC, veteran29 approved these changes
LGTM

2023-05-13 22:31 UTC, merged