Skills - Implement Infantry man skill tree
Savage-Game-Design/Across-the-Fence pull request #26
Opened 2023-05-13 10:28 UTC by cerebral-314

- https://app.clickup.com/6631910/v/l/6acf6-1952
- ~~https://docs.google.com/spreadsheets/d/17mmOFfmvGePKPaiMfS4Xxzo5DbqLoE-tB_mW--oB3dU/edit#gid=944780773~~

2023-05-21 13:57 UTC, veteran29 requested changes

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/global/fn_skills_parseTreeCfg.sqf
>                  ["isActive", getNumber (_x >> "skillType") > 0],
There's no need for adding another property, if `isActive` is not true the skill is passive.

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_teachSkill.sqf
> +    Last Update: 2023-05-21
The function was not changed.
```suggestion
    Last Update: 2023-02-25
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/client/active/fn_skills_active_skillWheelActivate.sqf
> +private _cooldownUntil = time + (_skill get "cooldown"); // cooldown handling probably should be server-sided as well.
I don't see a point in comments like this in the code. If it's an issue bring it up in the channels and let's make a task for that.

I also don't think we need server side cooldowns right now, reconnecting to skip skill cooldown is a lot of hassle with how slow arma loads.

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/client/applicators/fn_skills_apply_hoofIt.sqf
> +        WARNING: This is ran on the client-side.
No point in this, this is in client side folder. All skill effects run client side.
```suggestion
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/client/applicators/fn_skills_apply_steadyAim.sqf
> +private _coef = [1 - (0.01 * _skillTreePoints), 0, 1] call BIS_fnc_clamp;
BI func is slow.
```suggestion
private _coef = (1 - 0.01 * _skillTreePoints) max 0 min 1;
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/client/applicators/fn_skills_apply_steadyAim.sqf
> +player setCustomAimCoef _coef; // Probably should store this in the db for stacking purposes.
Same as with other comment, also no point in storing in DB, if we would add any stacking one local function for aim modifiers will be enough.
```suggestion
player setCustomAimCoef _coef;
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/client/applicators/fn_skills_apply_athletic.sqf
> +private _coef = [1 - (_skillTreePoints * 0.1), 0.1, 1] call BIS_fnc_clamp;
BI func is 10 times slower.
```suggestion
private _coef = (1 - _skillTreePoints * 0.1) max 0.1 min 1;
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/global/fn_skills_getSkillTreePoints.sqf
> +		[_tree] call vgm_g_fnc_skills_getSkillTreePoints;
Missing description, spacing.

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/server/fn_skills_forgetSkills.sqf
> +    Last Update: 2023-05-21
The function was not changed.
```suggestion
    Last Update: 2023-02-28
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/server/network/fn_skills_handle_skillLearnRequest.sqf
> +[] remoteExecCall ["vgm_c_fnc_skills_reapply", _player];
I feel like it would be better to handle this client side, with event handler. See how skills that need to be re-applied on respawn are handled, `client/skills_preInit`.
```suggestion
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/server/network/fn_skills_handle_skillRespecRequest.sqf
> +[] remoteExecCall ["vgm_c_fnc_skills_reapply", _player];
This is exactly why I feel it should be in event handler. Duplication and fragmentation of logic into multiple areas.
```suggestion
```

2023-05-21 13:57 UTC, veteran29 commented on game/functions/systems/skills/client/fn_skills_reapply.sqf
> +private _skillType = switch (_type) do {
As mentioned earlier checking if skill is not active would be enough, alternative to this is that every skill that needs an update after other skills are learned could add it's own event handler in application function. Or addition of `appllyOnLearn` flag.

2023-05-21 14:02 UTC, cerebral-314 commented on game/functions/systems/skills/client/active/fn_skills_active_skillWheelActivate.sqf
> +private _cooldownUntil = time + (_skill get "cooldown"); // cooldown handling probably should be server-sided as well.
They're mostly for me actually... forgot to remove them.  Thanks

2023-05-21 14:14 UTC, veteran29 commented on game/configs/mission/cfg_skills.hpp
> +                    description = "Decreases stamina comsumption from current weight.";
I think we should use stringtable for "actual" skill implementations.

2023-05-21 14:14 UTC, veteran29 commented on game/functions/systems/skills/client/applicators/fn_skills_apply_hoofIt.sqf
> +systemChat "You feel a sudden burst of energy!";
Stringtable too.

2023-09-22 17:59 UTC, veteran29 commented
I think I'll move each tree skills into separate subfolders. 

`skill/actives/infantryman` etc.

2023-09-23 22:52 UTC, Spoffy requested changes

2023-09-23 22:52 UTC, Spoffy commented on game/functions/systems/skill/passives/fn_skill_passives_preInit.sqf
> +    _group = group player; // TODO remove after "group" in missions is merged
Think we can remove this now :)

2023-09-23 22:52 UTC, Spoffy commented on game/functions/systems/skill/passives/infantryman/fn_skill_passives_infantryman_overprepared.sqf
> +    if (_usedInMission isEqualTo _currentMission) exitWith {};
Is it worth using `isEqualRef` here, to avoid deep-comparing the hashmaps? Could also use the mission ID, but I think isEqualRef would be nicer.

2023-09-23 22:52 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_skillWheelActivate.sqf
> +private _cooldownUntil = time + _cooldownTime; // cooldown handling probably should be server-sided as well.
Are you thinking from a security point of view?

If so, I agree, though hackers zeroing the cooldown isn't much of a problem I think, so happy to leave this for the future. 

Could throw a 'TODO:' prefix on it if you think this is worth doing later (easier to find). 

TL;DR - I agree it's not worth doing right now.

2023-09-24 00:01 UTC, veteran29 commented on game/functions/systems/skills/client/active/fn_skills_active_skillWheelActivate.sqf
> +private _cooldownUntil = time + _cooldownTime; // cooldown handling probably should be server-sided as well.
Mostly for ultimate abuse, use skill, disconnect, connect, join mission in progress. Skills available again.

2023-09-24 18:15 UTC, veteran29 commented on game/functions/systems/skill/passives/infantryman/fn_skill_passives_infantryman_overprepared.sqf
> +    if (_usedInMission isEqualTo _currentMission) exitWith {};
I'm not a fan of reference checking in SQF, in case some logic in netmap handling changes it could easily break.

If the items are same reference there's zero performance benefit of using `isEqualRef`, `isEqualTo` starts with ref check.

```sqf
a = createHashMap;

for "_i" from 1 to 1e5 do {
	a set [_i, _i];
};

b = a;

// separate execution
// Execution Time: 0.0003 ms  |  Cycles: 10000/10000  |  Total Time: 3 ms
a isEqualTo b

// separate execution
// Execution Time: 0.0003 ms  |  Cycles: 10000/10000  |  Total Time: 3 ms
a isEqualRef b
```

```sqf
a = createHashMap;

for "_i" from 1 to 1e5 do {
	a set [_i, _i];
};

b = +a; // copy the hashmap

// separate execution
// Execution Time: 15.2306 ms  |  Cycles: 66/10000  |  Total Time: 1005 ms
a isEqualTo b

// separate execution
// Execution Time: 0.0003 ms  |  Cycles: 10000/10000  |  Total Time: 3 ms
a isEqualRef b;
```

2023-09-24 18:45 UTC, merged

2023-09-24 19:37 UTC, Spoffy commented on game/functions/systems/skill/passives/infantryman/fn_skill_passives_infantryman_overprepared.sqf
> +    if (_usedInMission isEqualTo _currentMission) exitWith {};
Fair enough, that makes sense! Thanks for clarifying!