Add backend logic for skill cooldown HUD
Savage-Game-Design/Across-the-Fence pull request #27
Opened 2023-05-13 14:32 UTC by veteran29

- title

2023-05-13 22:52 UTC, Spoffy requested changes
Looks great. One suggestion, and two fixes for bugs caused by me merging the event system changes (sorry!)

2023-05-13 22:52 UTC, Spoffy commented on game/functions/core/client/displays/fn_displayAbilityCooldown.sqf
> +            };
I think we could move this inside the `if` block above, and save ourselves from checking it every frame?

2023-05-13 22:52 UTC, Spoffy commented on game/functions/core/client/displays/fn_displayAbilityCooldown.sqf
> +            };
Or even:
```
if (_deltaT <= TICK_TIME) exitWith {
            _deltaT = _deltaT + diag_deltaTime;
            _thisArgs set [0, _deltaT];
}
```
And have the rest of the function run normally?

2023-05-13 22:52 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_assignSkillToSlot.sqf
> +    ["vgm_skills_active_slotted", [_slot, _skill]] call para_g_fnc_event_trigger;
`triggerLocal` now, apologies for the inconveniently timed merge :D

2023-05-13 22:52 UTC, Spoffy commented on game/functions/systems/skills/client/active/fn_skills_active_skillWheelActivate.sqf
> +["vgm_skills_active_activated", [_slot get "name", _skill]] call para_g_fnc_event_trigger;
`triggerLocal`

2023-05-14 22:56 UTC, veteran29 commented on game/functions/core/client/displays/fn_displayAbilityCooldown.sqf
> +            };
Changed it so it's not checked on every frame and improved the timer accuracy a little bit by carrying over the `mod` over the ticker value upon ticker "tick".

2023-05-19 22:11 UTC, Spoffy approved these changes

2023-05-19 22:15 UTC, merged