Leveling system, logging tweaks
Savage-Game-Design/Across-the-Fence pull request #32
Opened 2023-06-02 14:51 UTC by veteran29

Simple levelling system, players can gain experience, if the experience is over/equals the current level threshold they "complete" the level and gain the next one. Provides events for hooking by other components.

Additionally, I've done some cleanup of the logging in the `skills` component so it uses our gamemode logging functions.

I've used a similar approach with handling player init as in the `skills` component but I've used events instead of remote executing the functions, I think I like it this way more as it does not end up in so many functions (wanted to do it like this initially but the routing table based event system was not usable for that use case).

2023-06-20 20:02 UTC, Spoffy requested changes

2023-06-20 20:02 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_preInit.sqf
> +    if (owner _player isNotEqualTo remoteExecutedOwner) exitWith {
(_this # 4) for events is `originMachineId`. You could always use that instead of remoteExecutedOwner. Not sure there's a major benefit in this situation though.

2023-06-20 20:02 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_preInit.sqf
> +    if (owner _player isNotEqualTo remoteExecutedOwner) exitWith {
This is the exact signature:
```
    [_this param [DATA_PARAMETER_INDEX], _savedParameters, _eventName, _topic, _originMachineId] call _code;
```

2023-06-20 20:02 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_preInit.sqf
> +    [_player, 0] call vgm_s_fnc_leveling_addExperience;
What does adding 0 experience do for us here? Can we add the reason for its call here as a comment?

2023-06-20 20:02 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_addExperience.sqf
> +};
I think we also need to set "experience" to 0, so that they start building up experience for the next level again.

As is, if they got the 500 xp to reach level 1, I think they'd still be on 500, and need only another 75xp to advance again?

2023-06-20 20:02 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_addExperience.sqf
> +    ["vgm_leveling_levelGained", [_player, _currentLevelData]] call para_g_fnc_event_triggerLocal;
We might want to make this a global event, or send it to the levelling up player's client, in the future.

2023-06-23 13:41 UTC, veteran29 commented on game/functions/systems/leveling/server/fn_leveling_preInit.sqf
> +    if (owner _player isNotEqualTo remoteExecutedOwner) exitWith {
`0.000185456`ms vs `0.000253346`ms and the intent is more clear with `remoteExecutedOwner` so I'll stick with it.

2023-06-23 14:06 UTC, veteran29 commented on game/functions/systems/leveling/server/fn_leveling_preInit.sqf
> +    [_player, 0] call vgm_s_fnc_leveling_addExperience;
It's used to trigger level up from 0 to 1 and broadcast the data to client, added comment.

2023-06-23 14:24 UTC, veteran29 commented on game/functions/systems/leveling/server/fn_leveling_addExperience.sqf
> +};
I've added `experienceThreshold` key to the Level HashMaps which holds whole sum of experience needed to complete the level.

2023-06-23 14:27 UTC, veteran29 commented on game/functions/systems/leveling/server/fn_leveling_addExperience.sqf
> +    ["vgm_leveling_levelGained", [_player, _currentLevelData]] call para_g_fnc_event_triggerLocal;
I want this event to be "sync" with this code, ~~I'll add target event below.~~

Used globalEvent

2023-06-23 18:10 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_preInit.sqf
> +    if (owner _player isNotEqualTo remoteExecutedOwner) exitWith {
Yup, all good! And headless clients aren't a worry here either :)

2023-06-23 22:33 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_addExperience.sqf
> +    ["vgm_leveling_levelGained", [_player, _currentLevelData]] call para_g_fnc_event_triggerLocal;
This makes me realise why the other change in my PR to the event system is... irritating. 😆

2023-06-23 22:43 UTC, Spoffy commented on game/functions/systems/leveling/server/fn_leveling_addExperience.sqf
> +    ["vgm_leveling_levelGained", [_player, _currentLevelData]] call para_g_fnc_event_triggerLocal;
I'll revert the change in mine, so all good here.

2023-06-23 22:43 UTC, Spoffy approved these changes

2023-06-25 11:58 UTC, merged