Medical system backend
Savage-Game-Design/Across-the-Fence pull request #33
Opened 2023-06-19 10:16 UTC by veteran29

2023-07-06 22:58 UTC, veteran29 commented
Ready for review, the backend is mostly done.

There are few things that could use further work but it should be reasonable to do them in the following pull requests, namely:
- Most of the debuffs are not implemented, we lack a coefficient system for them, should be done separately
- The way the debuffs are checked in the `add/remove wound` functions feels ugly, could be refactored
- No progress bars and item consumption on healing
- Fall damage needs handling
- Burning damage needs handling
- Drowning needs handling

2023-07-06 22:58 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_addWound.sqf
> +        N/A
Missing docs.

2023-07-06 22:58 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_preInit.sqf
> +    _player addAction ["Heal", {}];
Medical menu needs to be added on this action.

2023-07-06 22:58 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_postInit.sqf
> +                _unit setUnconscious true;
Could be refactored into a separate function that emits an event upon consciousness change.

2023-07-06 22:58 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_receiveDamage.sqf
> + */
Docs.

2023-07-06 22:58 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> + */
Docs.

2023-07-09 14:58 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_preInit.sqf
> +    _player addAction ["Heal", {}];
Is this just the final medical menu? As we could put it in a comment here.

2023-07-09 16:57 UTC, Spoffy requested changes

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_postInit.sqf
> +} forEach ((allPlayers select {!(_x isKindOf "VirtualMan_F")}) - [player]);
I don't recognise this classname, what're we removing from this loop? :)

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_postInit.sqf
> +        if (_deltaT >= TICK_TIME) then {
Could refactor this to be `if (_deltaT <= TICK_TIME) exitWith {}`, and move `_thisArgs set [0, _deltaT]` to below `_deltaT =`. Might be a little neater with less indentation?

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_postInit.sqf
> +                _unit setUnconscious true;
Might be worth emitting an event on conciousness change anyway, even if we don't refactor now, so other systems can hook into it.

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_receiveDamage.sqf
> +    format ["(Medical) Invalid HitPoint: %1", _hitPoint] call vgm_g_fnc_logError;
Maybe worth switching to warning? As it's not going to have much of an impact I think if there's a missing hitpoint somehow.

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +};
I think check should be related to when `setUnconscious` is done in `addWound`. For example, if a player is hit by an explosion, which does:
- 3 wounds to the head
- 3 wounds to the arm

Then they fall unconscious from the head wound. But healing the head wound wouldn't get them up, they'd need the arm healing 1 stage too.

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +};
Maybe we could pull this and the bleed check in `addWound` out into its own function? Think it's an easy source of bugs having the condition for bleeding duplicated.

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +};
Maybe we could put this under the bleed removal too? Just to be 9999% sure the bleed event handler won't get called again knocking them unconscious? 

I realise it's probably not possible, but feels like a sensible precaution we could take?

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +    };
Won't review this for now, since there's a lot of behaviours missing.

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/script_component.inc
> +#define DMG_3 0.9
Are these used? Not seeing any references when searching, but I'm in PR view so could have missed something.

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/script_component.inc
> +#define TYPE_BACKPACK 901
Are these used? Not seeing anything when searching, but only using Ctrl-F in the browser.

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_openMedicalMenu.sqf
> + */
Docs. Or will this function be replaced by the actual medical menu later?

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_itemApplyMedikit.sqf
> + */
Docs

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_itemApplyFAK.sqf
> + */
Docs

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_itemApplyFAK.sqf
> +["vgm_medical_heal", [_healer, _patient, "fak", _bodyPart], [_patient]] call para_g_fnc_event_triggerTargets;
I like the way you've used the event system in the medical system, it's clean 🙂

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_handleDamage.sqf
> +if (!local _unit) exitWith {};
Did not know this, nice comment :)

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_getArmorItem.sqf
> +            getNumber (_unitCfg >> "armor") * (1 max getNumber (_entry >> "armor")) // return
We normalize the damage using the unit's hitpoint armor in receiveDamage line 30. Are we multiplying by that value again here, resulting in us using it twice?

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_fullHeal.sqf
> +        Fully heal an unit.
Does the unit need to be local? (i.e, this needs remoteExec'ing to heal another player?)
If so, could we add that to the docs? :)

2023-07-09 16:57 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_addWound.sqf
> +};
As mentioned in removeWound, could we move the "Should be bleeding" condition out to a separate function? Prevents them accidentally de-syncing then if one is modified and not the other.

2023-07-14 14:33 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_postInit.sqf
> +} forEach ((allPlayers select {!(_x isKindOf "VirtualMan_F")}) - [player]);
Virtual Curator, Spectator, Headless Client, any playable "unit" that has no body.

2023-07-14 22:42 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +};
> Then they fall unconscious from the head wound. But healing the head wound wouldn't get them up, they'd need the arm healing 1 stage too.

That was my intention, once somebody goes down you need to treat all of their severe wounds to bring them back. Otherwise, you could bring somebody with level 3 arms wounds, wouldn't that mean that he should start bleeding right after waking up?

2023-07-14 23:13 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_getArmorItem.sqf
> +            getNumber (_unitCfg >> "armor") * (1 max getNumber (_entry >> "armor")) // return
`receiveDamage` is passed the _raw_ hit damage from `handleDamage` which uses the HitPoint armor to detect which HitPoint was actually hit. `receiveDamage` then does it's own normalization, all is as intended.

2023-07-14 23:19 UTC, veteran29 commented on game/functions/systems/medical/client/script_component.inc
> +#define TYPE_BACKPACK 901
Only `TYPE_UNIFORM` is used right now.

2023-07-23 16:19 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_postInit.sqf
> +        if (_deltaT >= TICK_TIME) then {
We do `_deltaT = _deltaT mod TICK_TIME;` inside the if so the `_thisArgs` has to be updated after that. I think it's fine as is, it's the same in `vgm_c_fnc_displayAbilityCooldown`

2023-07-23 16:23 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_preInit.sqf
> +    _player addAction ["Heal", {}];
It's the dev menu right now but the same function will launch the final one once it's done.

2023-07-23 17:19 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_openMedicalMenu.sqf
> + */
This will open the final medical menu.

2023-07-23 17:43 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_addWound.sqf
> +};
Done.

2023-07-23 17:44 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +};
Done.

2023-07-23 18:01 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_postInit.sqf
> +                _unit setUnconscious true;
Added an function for conciousness change with events.

2023-07-23 18:09 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_fullHeal.sqf
> +        Fully heal an unit.
Wound variables are global but should be handled where the unit is local. Added info.

2023-07-23 18:10 UTC, veteran29 commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +    };
To be added in follow up PRs.

2023-07-27 22:19 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_removeWound.sqf
> +};
You make a good point, and the revive condition is definitely something that we missed from the designs. 

I think this works well for now, and we can revisit it after some playtesting 🙂

2023-07-27 23:19 UTC, Spoffy commented on game/functions/systems/medical/client/fn_medical_getArmorItem.sqf
> +            getNumber (_unitCfg >> "armor") * (1 max getNumber (_entry >> "armor")) // return
👍, thanks for clarifying 🙂

2023-07-27 23:27 UTC, Spoffy approved these changes

2023-07-27 23:47 UTC, merged