Add status effect API
Savage-Game-Design/Across-the-Fence pull request #34
Opened 2023-07-05 01:41 UTC by veteran29

- Simple API that allows us to toggle status effects like `forceWalk` etc. from multiple components. It will be used by stamina and medical systems.

2023-07-05 01:59 UTC, cerebral-314 commented on game/functions/core/client/statusEffect/fn_statusEffect_preInit.sqf
> +["forceWalk", {
Are we initializing/creating all future status effects here?

2023-07-05 11:00 UTC, veteran29 commented on game/functions/core/client/statusEffect/fn_statusEffect_preInit.sqf
> +["forceWalk", {
No, only the (common) ones that are related to built-in commands. For example something like "bleeding" related to the medical system should be handled in its own component.

2023-07-07 21:14 UTC, Spoffy requested changes
Few comments, but I like the way this system works :)

2023-07-07 21:14 UTC, Spoffy commented on game/functions/core/client/statusEffect/fn_statusEffect_create.sqf
> +vgm_c_statusEffect_map set [_name, _fnc_onChange];
Maybe we could change `vgm_c_statusEffect_map` to `vgm_c_statusEffect_allEffects`? 

Makes it a little clearer what it is, but it also helps with it having the same name as the unit variable, which tripped me up when initially reading the code :)

2023-07-07 21:14 UTC, Spoffy commented on game/functions/core/client/statusEffect/fn_statusEffect_get.sqf
> +private _effectMap = _unit getVariable ["vgm_c_statusEffect_map", createHashMap];
Similarly, maybe this one could become `vgm_c_statusEffect_currentEffects`? Or `vgm_c_statusEffect_currentEffectsMap`?

2023-07-07 21:14 UTC, Spoffy commented on game/functions/core/client/statusEffect/fn_statusEffect_preInit.sqf
> +}] call vgm_c_fnc_statusEffect_create;
Potential future race condition here if we have other systems register their own effects. If they register in `preInit`, `vgm_c_statusEffect_map` might not exist.

If they register in `postInit`, they might be registered after another system tries to apply them.

For now, maybe we could make `vgm_c_fnc_statusEffect_create` create `vgm_c_statusEffect_map` if it doesn't exist?

2023-07-07 21:14 UTC, Spoffy commented on game/functions/core/client/statusEffect/fn_statusEffect_remove.sqf
> +};
What do you think to just returning if the map doesn't exist? As none of the remaining code can trigger anyway (no effect).

2023-07-07 21:14 UTC, Spoffy commented on game/functions/core/client/statusEffect/fn_statusEffect_set.sqf
> +if (_reason in _reasonList) exitWith {};
For each effect, I'd probably have used a hashmap/set of reasons, to prevent duplicates.

I'm not suggesting we change it, I'm just curious what the motivation was behind using an array? 🙂

2023-07-07 21:14 UTC, Spoffy commented on game/functions/core/client/statusEffect/fn_statusEffect_set.sqf
> +private _effectsMap = _unit getVariable "vgm_c_statusEffect_map";
Do we need to wipe status effects when a player dies? As I think this would carry over to their new unit?

2023-07-11 23:45 UTC, veteran29 commented on game/functions/core/client/statusEffect/fn_statusEffect_set.sqf
> +if (_reason in _reasonList) exitWith {};
I just needed a simple data structure to hold few strings so just went with an array. Will refactor to HashMap.

2023-07-11 23:59 UTC, veteran29 commented on game/functions/core/client/statusEffect/fn_statusEffect_set.sqf
> +private _effectsMap = _unit getVariable "vgm_c_statusEffect_map";
Yeah, object variables persist on respawn.

2023-07-12 00:03 UTC, veteran29 commented on game/functions/core/client/statusEffect/fn_statusEffect_set.sqf
> +if (_reason in _reasonList) exitWith {};
Looking at it again, HashMap has no benefits here. I still need to do the `if (_reason in _reasonList) exitWith {};` check, if I won't, the repeated set of same `reason` will trigger `onChange` callback.

2023-08-19 00:57 UTC, Spoffy commented on game/functions/core/client/statusEffect/fn_statusEffect_set.sqf
> +if (_reason in _reasonList) exitWith {};
Yup, good point! I don't think there's enough reasons then to bother changing it 🙂

2023-08-19 00:57 UTC, Spoffy approved these changes

2023-08-19 07:22 UTC, merged