Medical - Refactor debuff/injury handling
Savage-Game-Design/Across-the-Fence pull request #50
Opened 2023-09-02 17:44 UTC by veteran29

- Move all debuff definitions into a hashmap
- Minor logging cleanup

2023-09-07 15:20 UTC, Spoffy requested changes

2023-09-07 15:20 UTC, Spoffy commented on game/functions/systems/medical/client/injuryEffects/fn_medical_injuryEffectsUpdate.sqf
> +    _unit call (_injuryEffects get "code");
Do we need a way to 'undo' the code changes? E.g We've got the one that sets players unconcious, but what restores them to conciousness?

2023-09-07 18:50 UTC, veteran29 commented on game/functions/systems/medical/client/injuryEffects/fn_medical_injuryEffectsUpdate.sqf
> +    _unit call (_injuryEffects get "code");
Code of previous level should "undo" anything that there's to undo. Right now healing logic handles waking up from unconsciousness.

2023-09-08 12:58 UTC, Spoffy approved these changes

2023-09-08 13:38 UTC, merged