Loading - Add component
Savage-Game-Design/Across-the-Fence pull request #54
Opened 2023-09-09 00:22 UTC by veteran29

Add new loading system with API that allows other components to register their own handlers which tell us if the component is ready.

Removes bunch of calls to legacy MF stuff.

2023-09-14 12:41 UTC, Spoffy requested changes

2023-09-14 12:41 UTC, Spoffy commented on game/functions/core/client/loading/fn_loading_postInit.sqf
> + */
Docs 🙂

2023-09-14 12:41 UTC, Spoffy commented on game/functions/core/client/loading/fn_loading_postInit.sqf
> +    "vgm_loading" call BIS_fnc_endLoadingScreen;
Having a bit of difficulty understanding the behaviour here. I read this as:
* Call all handlers to start loading, delete if it's done.

* Update text with something like:
 ```
 Loading.... System1
 System2
 System3
 ```
 
 * Update loading bar with a % based on how many handlers haven't yet returned true.
 
 
Does that sound right?

2023-09-14 12:41 UTC, Spoffy commented on game/functions/core/client/loading/fn_loading_postInit.sqf
> +    "vgm_loading" call BIS_fnc_endLoadingScreen;
It's worth adding some kind of fallback to this function. If a script errors, we'll get locked in the loading screen and have to restart Arma I believe.

2023-09-14 12:41 UTC, Spoffy commented on game/functions/core/client/loading/fn_loading_postInit.sqf
> +    "vgm_loading" call BIS_fnc_endLoadingScreen;
Can you shoot while on the loading screen? I vaguely recall that being the reason we originally disabled player simulation while loading.

2023-09-15 15:09 UTC, veteran29 commented on game/functions/core/client/loading/fn_loading_postInit.sqf
> +    "vgm_loading" call BIS_fnc_endLoadingScreen;
> Does that sound right?

yes

> Can you shoot while on the loading screen? I vaguely recall that being the reason we originally disabled player simulation while loading.

No, if you `BIS_fnc_startLoadingScreen` during `initFunctions` `postInit` it will be added to the "stack" of loading screens. Control over player avatar is given after all of them are done. I think you needed that as you did not use BI func and fired the loading screen at some later point of execution.

2023-09-15 15:15 UTC, veteran29 commented on game/functions/core/client/loading/fn_loading_postInit.sqf
> +    "vgm_loading" call BIS_fnc_endLoadingScreen;
> It's worth adding some kind of fallback to this function.

I think we need a timeout, but what should it do? In "production" it should probably kick you from the game telling you that something went wrong. Not sure about dev, maybe kick if no debug console and print an error and close loading screen if player has access to it?

2023-09-15 17:53 UTC, veteran29 commented on game/functions/core/client/loading/fn_loading_postInit.sqf
> +    "vgm_loading" call BIS_fnc_endLoadingScreen;
Added kick for standard user and error message for admins/debug console users after a 30s timeout.

2023-09-22 04:20 UTC, Spoffy approved these changes

2023-09-22 07:00 UTC, merged