Missions - Add group, change event names
Savage-Game-Design/Across-the-Fence pull request #58
Opened 2023-09-20 14:19 UTC by veteran29

- title

2023-09-20 18:40 UTC, Spoffy requested changes

2023-09-20 18:40 UTC, Spoffy commented on game/functions/systems/missions/client/internal/fn_missions_finishDeploy.sqf
> +[player] joinSilent (_currentMission get "group");
What do you think to joining players to the group when they join the mission (attachPlayerToMission function), rather than when deployment finishes on the client?

2023-09-20 18:40 UTC, Spoffy commented on game/functions/systems/missions/server/fn_missions_endMission.sqf
> +units (_missionPublic get "group") joinSilent vgm_core_lobbyGroup;
Similar to the other comment, I'm wondering if this should belong in `removePlayerFromMission`?

2023-09-21 20:46 UTC, veteran29 commented on game/functions/systems/missions/server/fn_missions_endMission.sqf
> +units (_missionPublic get "group") joinSilent vgm_core_lobbyGroup;
Not sure where it should belong as there's a lot of similar functions ;D moved group handling to attach/remove functions.

2023-09-22 04:17 UTC, Spoffy approved these changes

2023-09-22 07:01 UTC, merged