Skills - Implement Recon skill tree
Savage-Game-Design/Across-the-Fence pull request #61
Opened 2023-09-23 12:23 UTC by veteran29

- depends on #26

2023-10-10 22:03 UTC, Spoffy requested changes

2023-10-10 22:03 UTC, Spoffy commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +private _enemySides = playerSide call BIS_fnc_enemySides;
BIS_fnc_enemySides can be super expensive, it's really badly written. Though with how often we actually call it here, I don't think it'll be a problem.

2023-10-10 22:03 UTC, Spoffy commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +} forEach _enemies;
If we moved this below the `inAreaArray`, and used that list, we could make this significantly cheaper I think?

2023-10-10 22:03 UTC, Spoffy commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +            _x getVariable "vgm_c_objectColor",
Can I suggest making the alpha fade with distance? From experience in MF, it gets very noisy if there's a lot of these drawn on screen at once.

2023-10-10 22:03 UTC, Spoffy commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +        // TODO needs design
What's this TODO for?

2023-10-10 22:03 UTC, Spoffy commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_betterAim.sqf
> +private _killedEH = player addEventHandler ["Killed", _fnc_clearEH];
This is a horrible bug, nice job catching it + commenting why it's needed.

2023-10-10 22:03 UTC, Spoffy commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_followTheTracers.sqf
> +            [1,0,0,1],
Might want to fade this one too, but let's see how it goes.

2023-10-10 22:03 UTC, Spoffy commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_keenEye.sqf
> +    private _distance = _from vectorDistance _lookPosASL;
For my own benefit, what's the advantage of this over `screenToWorld`?

2023-10-11 00:18 UTC, veteran29 commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_keenEye.sqf
> +    private _distance = _from vectorDistance _lookPosASL;
`screenToWorld` works only for terrain. Above will give you correct point you're looking at, or if it's at the view distance limit/looking at sky it will give you a point in the air `viewDistance` from you.

https://github.com/Savage-Game-Design/Across-the-Fence/assets/4293906/a1877bfa-9958-44cb-893b-a3f8f3320a2c

2023-10-13 14:19 UTC, Spoffy commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_keenEye.sqf
> +    private _distance = _from vectorDistance _lookPosASL;
Huh, I never knew that - thanks for the explanatory video :)

2023-10-14 01:15 UTC, veteran29 commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +private _enemySides = playerSide call BIS_fnc_enemySides;
I wouldn't say it's super expensive, but it's not written optimally. I've added `vgm_g_fnc_enemySides` that's twice as fast.

2023-10-14 01:15 UTC, veteran29 commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +} forEach _enemies;
Good catch.

2023-10-14 01:15 UTC, veteran29 commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +        // TODO needs design
For making the icons look properly but it's done. Removed comment.

2023-10-14 01:46 UTC, veteran29 commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +            _x getVariable "vgm_c_objectColor",
Added.

2023-10-14 01:46 UTC, veteran29 commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_followTheTracers.sqf
> +            [1,0,0,1],
Added.

2023-10-28 15:43 UTC, Spoffy commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +            _x getVariable "vgm_c_objectColor",
Did you push this change? Not seeing anything :)

2023-10-28 15:43 UTC, Spoffy commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_followTheTracers.sqf
> +            [1,0,0,1],
Did you push this change? Not seeing anything :)

2023-10-28 16:16 UTC, Spoffy commented on game/functions/systems/skill/client/actives/recon/fn_skill_actives_recon_sixthSense.sqf
> +            _x getVariable "vgm_c_objectColor",
Found it in the other PR!

2023-10-28 16:16 UTC, Spoffy commented on game/functions/systems/skill/client/passives/recon/fn_skill_passives_recon_followTheTracers.sqf
> +            [1,0,0,1],
Found it in the other PR!

2023-10-29 14:52 UTC, merged