Skills - Implement Fire Support skill tree
Savage-Game-Design/Across-the-Fence pull request #68
Opened 2023-10-08 16:21 UTC by veteran29

Depends on #61 - Review after it's merged to have proper diff

2023-10-13 16:17 UTC, Spoffy requested changes

2023-10-13 16:17 UTC, Spoffy commented on game/functions/systems/skill/client/actives/fire_support/fn_skill_actives_fireSupport_grenadesCase.sqf
> +["skill_active_sixthSense", {
Think this runLater name needs an update? :)

2023-10-13 16:17 UTC, Spoffy commented on game/functions/systems/skill/client/actives/fire_support/fn_skill_actives_fireSupport_overwhelmingFire.sqf
> +["skill_active_sixthSense", {
Same here r.e. runLater name :)

2023-10-13 16:17 UTC, Spoffy commented on game/mission/stringtable.xml
> +        <Key ID="STR_VGM_SKILLS_SKILL_FIRE_SUPPORT_LEARN_THE_RHYHTM_DESC">
Typo in these string names, should be RHYTHM P)

2023-10-13 16:17 UTC, Spoffy commented on game/configs/mission/cfg_skills.hpp
> +                    description = "$STR_VGM_SKILLS_SKILL_FIRE_SUPPORT_LEARN_THE_RHYHTM_DESC";
Typo in RHYTHM here :)

2023-10-13 17:34 UTC, veteran29 commented on game/mission/stringtable.xml
> +        <Key ID="STR_VGM_SKILLS_SKILL_FIRE_SUPPORT_LEARN_THE_RHYHTM_DESC">
Damn this word, I keep typoing it all the time. In Polish it's just `rytm`.

2023-10-28 16:07 UTC, Spoffy commented on game/mission/stringtable.xml
> +        <Key ID="STR_VGM_SKILLS_SKILL_FIRE_SUPPORT_LEARN_THE_RHYHTM_DESC">
Hah, I like the simplicity of the polish word :D

2023-10-28 16:07 UTC, Spoffy approved these changes

2023-10-29 14:56 UTC, merged