Equipment - Filter loadouts in arsenal
Savage-Game-Design/Across-the-Fence pull request #83
Opened 2023-11-19 17:01 UTC by veteran29

- loadout filtering on arsenal close and template loadout loading
- dependent on gear available to player (`vgm_equipment`)

2023-11-19 21:21 UTC, Spoffy commented on game/functions/systems/equipment/client/fn_equipment_arsenalInit.sqf
> +}] call BIS_fnc_addScriptedEventHandler;
❤️

2023-11-19 21:36 UTC, Spoffy requested changes
Overall looks good! 

Couple of proposed tweaks :)

2023-11-19 21:36 UTC, Spoffy commented on game/functions/systems/equipment/client/fn_equipment_filterLoadout.sqf
> +        // TODO is it possible to have container in container?
Yup, turns out you can have vests and uniforms inside backpacks. Here's what it looks like:
```
[[],[],[],[],[],["vn_c_pack_02",[["vn_o_vest_04",false],["vn_b_uniform_macv_03_17",false]]],"","",[],["vn_b_item_map","","vn_b_item_radio_urc10","vn_b_item_compass_sog","vn_b_item_watch",""]]
```
probably worth addressing now, as players will definitely find this loophole :D

2023-11-19 21:36 UTC, Spoffy commented on game/functions/systems/equipment/client/fn_equipment_filterLoadout.sqf
To me, `fn_equipment_filterLoadout` to be a little shennanigany, modifying its input array when the functions are called 'check'.

The backpack one where it literally resizes _this threw me off for a minute, until I realised _this was a reference to the backpack entry in the loadout array :D

As a cheap change, can I propose we rename `fn_checkX` functions to `fn_filterX` or `removeForbiddenFromX`? I think it more strongly implies it's doing some work on the input arrays.

I'd probably prefer something like `_loadout set [_x, _newEntry]` in the filter loops, but I don't think it's worth the time spent making that change.

2023-11-20 18:24 UTC, veteran29 commented on game/functions/systems/equipment/client/fn_equipment_filterLoadout.sqf
> I'd probably prefer something like _loadout set [_x, _newEntry] in the filter loops, but I don't think it's worth the time spent making that change.

It's bit hard to follow but it's a lot easier to just modify via ref, that's why I went with it.

I agree on the naming change, the function originally was called `checkGear` and I forgot to change the internal functions.

2023-11-25 01:07 UTC, Spoffy approved these changes
Awesome, thanks for making those changes, it definitely felt easier to understand! :)

2023-11-25 01:17 UTC, merged