Coefficient - Add override system
Savage-Game-Design/Across-the-Fence pull request #96
Opened 2023-11-26 17:13 UTC by veteran29

- title

Allows us to temporarily override/pause the coefficient system callbacks while still allowing to change the coefficient reasons/values. This allows us to for example set the value of `setAnimSpeedCoef` for the duration of the item apply animation.

Needed for medical anims and drag/carry.

2023-11-26 17:17 UTC, veteran29 commented
Example usage:
```sqf
[player, "animSpeed", "system1", 0.2] call vgm_c_fnc_coefficient_set;
// player anim speed is 1.2

[player, "animSpeed", "medical_item", true] call vgm_c_fnc_coefficient_override;
// player anim speed is 1.2

player setAnimSpeedCoef 0.5;
// player anim speed is 0.5

[player, "animSpeed", "system2", 0.1] call vgm_c_fnc_coefficient_set;
// player anim speed is 0.5

[player, "animSpeed", "medical_item", false] call vgm_c_fnc_coefficient_override;
// player anim speed is 1.3
```

2023-11-30 23:33 UTC, Spoffy requested changes

2023-11-30 23:33 UTC, Spoffy commented on game/functions/core/client/coefficient/fn_coefficient_override.sqf
> +// set a reason if there's one, onChange function will always be applied
Am I right in thinking this comment isn't valid? As if we don't provide a reason, we exit out?

2023-12-11 21:00 UTC, Spoffy approved these changes

2023-12-11 21:01 UTC, merged